id = "1"
question = "Who is the first and chiefest being?"

[[sections]]
text = "God is the first and chiefest being"
verses = "Isaiah 44:6; Psalm 8:1; Psalm 97:9"

[[sections]]
text = "such that all other beings and causes are subordinate to Him."
verses = "1 Corinthians 8:6; Romans 11:36"

[[sections]]
text = "He is chiefest in heaven and earth"
verses = "Psalm 89:6; Psalm 56:2; Exodus 15:11"

[[sections]]
text = "so that in all things He might have the preeminence."
verses = "Colossians 1:18; Psalm 92:8"
