id = "2"
question = "Ought everyone to believe that there is a God?"

[[sections]]
text = "Everyone ought to believe that there is a God, for the being of God is the foundation of all practical religion"
verses = "Hebrews 11:6; Romans 10:14"

[[sections]]
text = "and the chief and highest purpose for which man was created."
verses = "Romans 11:36; 1 Corinthians 6:20; 1 Corinthians 10:31; Psalm 86:9, 12"

[[sections]]
text = "It is their great sin"
verses = "Jeremiah 4:22; 1 Corinthians 15:34"

[[sections]]
text = "and folly"
verses = "Psalm 14:1; Psalm 53:1"

[[sections]]
text = "who do not believe in Him."
verses = ""