id = "3"
question = "How may we know there is a God?"

[[sections]]
text = "The light of nature in man"
verses = "Romans 1:18-19; Acts 17:28; Proverbs 20:27"

[[sections]]
text = "and the works of God"
verses = "Romans 1:20; Psalm 19:1-3; Psalm 139:14; Job 12:7; Job 12:9; Psalm 9:16; Acts 14:17; Isaiah 46:9-10; Isaiah 41:21-29"

[[sections]]
text = "plainly declare there is a God, but His Word and Spirit only do fully and effectually reveal Him unto men for the salvation of sinners."
verses = "1 Corinthians 2:9-10; 1 Corinthians 1:20-21; 2 Timothy 3:14-15; Isaiah 59:21"
