id = "4"
question = "What is the chief and highest end of man?"

[[sections]]
text = "Man's chief and highest end is to glorify God fully"
verses = "Romans 11:36; 1 Corinthians 6:20; 1 Corinthians 10:31; Psalm 86:9, 12"

[[sections]]
text = "and to enjoy Him completely forever."
verses = "Psalm 73:24-28; John 17:20-23; Psalm 16:5-11; Revelation 21:3-4; Revelation 19:7-9"
