id = "5"
question = "What is the Word of God?"

[[sections]]
text = "The Holy Scriptures of the Old and New Testament, being given by divine inspiration, are the Word of God,"
verses = "2 Timothy 3:15-17; 2 Peter 1:16-21; 2 Peter 3:2, 15-16"

[[sections]]
text = "and the only certain rule of faith and obedience."
verses = "Deuteronomy 4:1-2; Revelation 22:18-19; Isaiah 8:19-20; Luke 16:19-31"