id = "6"
question = "May all men make use of the Holy Scriptures?"

[[sections]]
text = "All men are not only permitted, but commanded and exhorted to read, to hear, and to be careful to understand the Holy Scriptures."
verses = "John 5:38; Revelation 17:18-19; Revelation 1:3; Acts 8:30"

[[sections]]
text = "The Holy Scriptures should be read attentively and diligently,"
verses = "Luke 10:26; John 10:39; Deuteronomy 17:19"

[[sections]]
text = "and heard with holy reverence,"
verses = "Isaiah 66:2"

[[sections]]
text = "with delight,"
verses = "Mark 12:37"

[[sections]]
text = "with meekness,"
verses = "James 1:21"

[[sections]]
text = "with settled resolutions of obedience,"
verses = "Deuteronomy 32:46"

[[sections]]
text = "and in faith."
verses = "2 Chronicles 20:20"
