id = "7"
question = "How may we know that the Scriptures are the Word of God?"

[[sections]]
text = "The Scriptures manifest themselves to be the Word of God by the majesty of its style and purity of its doctrines;"
verses = "Psalm 12:6; Psalm 19:7-8; Psalm 119:18, 129, 140; 1 Corinthians 2:6-7"

[[sections]]
text = "by the consent of all the parts and the scope of the whole,"
verses = "Luke 24:25-27; Acts 10:43; Acts 26:22-23"

[[sections]]
text = "which is to give all glory to God;"
verses = "Romans 16:25-27; John 16:13-14"

[[sections]]
text = "and by its power to convert sinners and to edify saints unto salvation."
verses = "Acts 18:24-28; Hebrews 4:12-13; James 1:18; Psalm 19:7-9; Romans 15:4; Acts 20:32"

[[sections]]
text = "However, the Spirit of God alone, bearing witness by and with the Scriptures in the heart of man, is able fully to persuade it that they are the very Word of God."
verses = "John 16:13-14; 1 John 2:20, 27; John 20:31"
