id = "8"
question = "What do the Scriptures principally teach?"

[[sections]]
text = "The Scriptures principally teach what man is to believe concerning God"
verses = "Exodus 34:5-7; John 20:31; 2 Timothy 3:15-16"

[[sections]]
text = "and what duty God requires of man."
verses = "Deuteronomy 10:12-13; 2 Timothy 3:15-17; Acts 16:30-31; Ecclesiastes 12:13; 1 Corinthians 10:11"
