id = "9"
question = "What do the Scriptures make known of God?"

[[sections]]
text = "The Scriptures make known what God is,"
verses = "John 4:24; John 20:31; Exodus 34:6-7; Isaiah 40:18-28"

[[sections]]
text = "the persons in the Godhead,"
verses = "Matthew 3:16-17; Deuteronomy 6:4; 1 Corinthians 8:6; Matthew 28:19-20; 2 Corinthians 13:14"

[[sections]]
text = "His decrees,"
verses = "Acts 15:14-18; Isaiah 46:9-11; 1 Corinthians 2:6-13"

[[sections]]
text = "and the execution of His decrees."
verses = "Acts 4:26-28; Acts 2:23; Ephesians 1:11"