id = "10"
question = "What is God?"

[[sections]]
text = "God is a Spirit,"
verses = "John 4:24"

[[sections]]
text = "who in and of himself is infinite in being,"
verses = "Exodus 3:14; Job 11:7-9; Psalm 145:3; Psalm 147:5"

[[sections]]
text = "glory,"
verses = "Psalm 24:7-10; John 1:14; Hebrews 1:3"

[[sections]]
text = "blessedness,"
verses = "1 Timothy 6:15; 1 Timothy 1:17"

[[sections]]
text = "and perfection."
verses = "Matthew 5:48; Exodus 15:11; 1 Peter 1:15-16; Revelation 15:34"

[[sections]]
text = "God is all-sufficient,"
verses = "Exodus 3:14; Romans 11:35-36; Acts 17:25"

[[sections]]
text = "eternal,"
verses = "Psalm 90:2; Deuteronomy 33:27; Hebrews 1:10-12"

[[sections]]
text = "unchangeable,"
verses = "Malachi 3:6; Hebrews 13:8; James 1:17"

[[sections]]
text = "incomprehensible,"
verses = "1 Kings 8:27; Romans 11:33-34; Psalm 145:3"

[[sections]]
text = "omnipresent,"
verses = "Psalm 139:1-13"

[[sections]]
text = "omnipotent,"
verses = "Genesis 17:1; Matthew 19:26; Ephesians 3:20"

[[sections]]
text = "omniscient,"
verses = "Hebrews 4:13; Psalm 147:5; Psalm 139:1-13"

[[sections]]
text = "most wise,"
verses = "Romans 11:33-34; Romans 16:27; Colossians 2:3; Psalm 92:5"

[[sections]]
text = "most holy and just,"
verses = "Deuteronomy 32:4; Romans 3:5, 26; Isaiah 6:3; Revelation 4:8-9; Revelation 15:4"

[[sections]]
text = "most merciful and gracious, long-suffering, and abundant with goodness and truth."
verses = "Exodus 34:6; Psalm 117:2; Deuteronomy 32:4"