id = "11"
question = "Is there more than one God?"

[[sections]]
text = "There is but one only: the living and true God."
verses = "Deuteronomy 6:4; Isaiah 45:21-22; Isaiah 44:6; Jeremiah 10:10"

[[sections]]
text = "Yet, there are three persons in the Godhead: the Father, the Son, and the Holy Ghost."
verses = "Matthew 3:16-17; Matthew 28:19; 1 Corinthians 8:6; 2 Corinthians 13:14"

[[sections]]
text = "These three are one true, eternal God, the same in substance, equal in power and glory; although distinguished by their personal properties."
verses = "John 1:1; Genesis 1:1-3; John 17:5; Hebrews 1:8-9; John 10:30; Acts 5:34"