id = "12"
question = "What are the personal properties of the three persons of the Godhead?"

[[sections]]
text = "From all eternity, it is proper to the Father to beget the Son,"
verses = "Hebrews 1:5-8"

[[sections]]
text = "and to the Son to be begotten of the Father,"
verses = "John 1:14-18; John 17:3"

[[sections]]
text = "and to the Holy Ghost to proceed from the Father and the Son."
verses = "John 15:26; Galatians 4:6"