id = "13"
question = "How may we know that the Son and the Holy Ghost are God, equal with the Father?"

[[sections]]
text = "The Scriptures manifest that the Son and the Holy Ghost are equal with the Father, ascribing unto them such names,"
verses = "Jeremiah 23:5-6; Psalm 45:6-7; Isaiah 6:3, 5, 8; John 12:41; Acts 28:25; 1 John 5:20; Acts 5:3-4"

[[sections]]
text = "attributes,"
verses = "John 1:1; Isaiah 9:6; John 2:24-25; 1 Corinthians 2:10-11"

[[sections]]
text = "works,"
verses = "Colossians 1:16; Genesis 1:2; Mark 2:1-10"

[[sections]]
text = "and worship"
verses = "Matthew 28:19; 2 Corinthians 13:14; Revelation 22:3"

[[sections]]
text = "as are proper to God only."
verses = ""