id = "14"
question = "What are the decrees of God?"

[[sections]]
text = "God's decrees are the wise, free, and holy acts from the purposes of His will,"
verses = "Isaiah 45:6-7; Ephesians 1:11; Romans 11:33; Romans 9:14-15, 18"

[[sections]]
text = "whereby, from all eternity, He has, in Himself and for His own glory, unchangeably foreordained whatsoever comes to pass in time, particularly concerning angels and men."
verses = "Psalm 33:11; Isaiah 14:24; Acts 2:23; Acts 4:27-28; Romans 9:22-23; Ephesians 1:4, 11"