id = "15"
question = "What has God particularly decreed concerning angels and men?"

[[sections]]
text = "By an eternal and immutable decree, which originates solely from His love and exists for the praise of His glorious grace to be manifested in due time, God has elected some angels to glory;"
verses = "1 Timothy 5:21; Matthew 16:27; Matthew 25:41; 2 Peter 2:4; Jude 6"

[[sections]]
text = "and in Christ has chosen some men for eternal life, along with the means thereof."
verses = "Ephesians 1:4-6; Ephesians 2:10; 2 Thessalonians 2:13-14; 1 Peter 1:2"

[[sections]]
text = "Additionally, in accordance with His sovereign power and the unsearchable purposes of His will (by which He extends or withholds favor as He pleases), God passed by and foreordained the rest to be inflicted with dishonor and wrath for their sin, to the praise of His glorious justice."
verses = "Romans 9:17-22; Matthew 11:25-26; 2 Timothy 2:20; Jude 4; 1 Peter 2:8"