id = "16"
question = "How does God execute His decrees?"

[[sections]]
text = "God executes His decrees in the works of creation and providence,"
verses = "Revelation 4:11; Isaiah 40:12-31"

[[sections]]
text = "according to His infallible foreknowledge and the free and immutable counsel of His own will."
verses = "Ephesians 1:11; Psalm 148:8; Daniel 4:35; Acts 4:24-28"