id = "17"
question = "What is the work of creation?"

[[sections]]
text = "The work of creation is, God's making all things, whether visible or invisible, out of nothing, by the Word of His power, in the space of six days, and all very good."
verses = "Genesis 1; Colossians 1:16; Psalm 33:6-9; Hebrews 11:3; Revelation 4:11"
