id = "18"
question = "How did God create angels?"

[[sections]]
text = "God created all the angels as immortal spirits,"
verses = "Colossians 1:16; Matthew 22:30; Luke 20:36; Psalm 104:4"

[[sections]]
text = "holy with superior knowledge"
verses = "Matthew 25:31; 2 Samuel 14:17; Matthew 24:36"

[[sections]]
text = "and mighty power,"
verses = "2 Thessalonians 1:7"

[[sections]]
text = "to execute His commandments and to praise His name."
verses = "Psalm 91:11-12; Psalm 103:20-21"

[[sections]]
text = "Yet they were subject to fall into sin and damnation."
verses = "2 Peter 2:4"
