id = "19"
question = "How did God create man?"

[[sections]]
text = "After God had made all other creatures, He created man – male and female."
verses = "Genesis 1:27; Matthew 19:4"

[[sections]]
text = "He formed the body of man from the dust of the ground and the woman from the rib of the man."
verses = "Genesis 2:7, 22"

[[sections]]
text = "He endued them with living, reasonable, and immortal souls"
verses = "Genesis 2:7; Ecclesiastes 12:7; Matthew 10:28; Job 35:11; Luke 23:43"

[[sections]]
text = "and made them after His own image"
verses = "Genesis 1:26-27"

[[sections]]
text = "in knowledge, righteousness, and holiness,"
verses = "Colossians 3:10; Ephesians 4:24"

[[sections]]
text = "having the law of God written in their hearts"
verses = "Romans 2:14-15"

[[sections]]
text = "and the power to fulfill it."
verses = "Ecclesiastes 7:29"

[[sections]]
text = "Moreover, He gave them dominion over all living creatures."
verses = "Genesis 1:28; Psalm 8:6-8"

[[sections]]
text = "Yet, they were subject to fall, being left to the liberty of their own will, which was subject to change."
verses = "Genesis 2:16-17; Genesis 3:6; Ecclesiastes 7:29"
