id = "20"
question = "What are God's works of providence?"

[[sections]]
text = "God's works of providence are His most holy,"
verses = "Psalm 145:17; Leviticus 21:8"

[[sections]]
text = "wise,"
verses = "Psalm 104:24; Isaiah 28:29"

[[sections]]
text = "and powerful preserving"
verses = "Hebrews 1:3; Psalm 36:6; Nehemiah 9:6"

[[sections]]
text = "and governing"
verses = "Psalm 103:19; Psalm 145:14-16; Job 38-41"

[[sections]]
text = "of all His creatures and all their actions"
verses = "Matthew 10:29-31; Genesis 45:7; Psalm 135:6"

[[sections]]
text = "to His own glory."
verses = "Romans 11:36; Isaiah 63:14"