id = "21"
question = "What is God's providence towards the angels?"

[[sections]]
text = "God, by His providence, permitted some of the angels, willfully and irrecoverably, to fall into sin and damnation,"
verses = "Jude 6; 2 Peter 2:4; Hebrews 2:16; John 8:44"

[[sections]]
text = "limiting and ordering their fall and all their sins to His own glory."
verses = "Job 1:12; Matthew 8:31; Luke 10:17"

[[sections]]
text = "God established the rest of the angels in holiness and happiness,"
verses = "1 Timothy 5:21; Mark 8:38; Hebrews 12:22"

[[sections]]
text = "employing them all,"
verses = "Psalm 103:20; Psalm 104:4"

[[sections]]
text = "according to His pleasure, as administrative agents of His power, mercy, and justice."
verses = "Hebrews 1:14; 2 Kings 19:35"