id = "22"
question = "What was the providence of God toward man in the estate in which he was created?"

[[sections]]
text = "God, by His providence, placed man in paradise, appointing him to dress it and keep it."
verses = "Genesis 2:8, 15"

[[sections]]
text = "God gave man the liberty to eat of the fruit of the earth,"
verses = "Genesis 2:16"

[[sections]]
text = "placed the creatures under his dominion,"
verses = "Genesis 1:28"

[[sections]]
text = "ordained marriage for his help,"
verses = "Genesis 2:18; Matthew 19:3-6; Ephesians 5:31"

[[sections]]
text = "afforded him communion with Himself,"
verses = "Genesis 1:26-28; Genesis 3:8"

[[sections]]
text = "and instituted the Sabbath."
verses = "Genesis 2:3; Exodus 20:11"

[[sections]]
text = "Moreover, God entered into a covenant of life with him upon condition of perfect obedience"
verses = "Genesis 2:16-17; Hosea 6:7; Romans 5:12-14"

[[sections]]
text = "(of which the tree of life was a pledge),"
verses = "Genesis 2:9; Genesis 3:22-24"

[[sections]]
text = "forbidding him to eat of the tree of the knowledge of good and evil, upon the pain of death."
verses = "Genesis 2:17; James 2:10"
