id = "23"
question = "Did our first parents continue in the estate wherein they were created?"

[[sections]]
text = "Our first parents, being left to the freedom of their will, through the temptation of Satan, sinned against God in eating the forbidden fruit and thereby, fell from the estate wherein they were created."
verses = "Genesis 3:6-13; 2 Corinthians 11:3"