id = "24"
question = "What is sin?"

[[sections]]
text = "Sin is any want of conformity unto, or transgression of, any law of God, given as a rule to the reasonable creature."
verses = "Leviticus 5:17; James 4:17; 1 John 3:4; Galatians 3:10-12"
