id = "25"
question = "Did all mankind fall in Adam's transgression?"

[[sections]]
text = "Since the covenant made with Adam was as a public person (not for himself only but for his posterity),"
verses = "Acts 17:26; Romans 3:23"

[[sections]]
text = "all mankind, descending from him by original generation, sinned in him and fell with him in that first disobedience."
verses = "Genesis 2:16-17; Genesis 3:16-19; Romans 5:12-20; 1 Corinthians 15:21-22"

[[sections]]
text = "The fall brought mankind into an estate of sin and misery."
verses = "Genesis 3:16-19; Romans 5:12; Ephesians 2:1; Romans 3:16-23"
