id = "26"
question = "Wherein consists the sinfulness of that estate whereinto men fell?"

[[sections]]
text = "The sinfulness of that estate whereinto man fell consists in the guilt of Adam's first sin, the want of original righteousness,"
verses = "Genesis 2:16-17; Romans 5:12-20; 1 Corinthians 15:21-22"

[[sections]]
text = "and the corruption of his whole nature, whereby he is utterly indisposed, disabled, and opposed to all that is spiritually good as well as being continually inclined to all evil, which is commonly called original sin;"
verses = "Romans 3:10-19; Romans 8:7-8; Genesis 6:5; 1 Corinthians 2:14"

[[sections]]
text = "together with all actual transgressions which proceed from it."
verses = "James 1:14-15; Psalm 53:1-3; Matthew 15:19; John 3:6"