id = "27"
question = "How is original sin conveyed from our first parents unto their posterity?"

[[sections]]
text = "Original sin is conveyed from our first parents unto their posterity by natural generation, so as all that proceed from them in that way are conceived and born in sin."
verses = "Psalm 51:5; Job 14:4; Job 15:14; John 3:6"