id = "28"
question = "What is the misery of that estate whereinto man fell?"

[[sections]]
text = "All mankind, by their fall, lost communion with God,"
verses = "Genesis 3:8, 10, 24; John 8:34, 42, 44; Ephesians 2:12"

[[sections]]
text = "are under His wrath and curse"
verses = "Genesis 3:16-19; Ecclesiastes 2:22-23; Romans 8:18-23"

[[sections]]
text = "such that we are by nature children of wrath"
verses = "Ephesians 2:2-3; John 3:36; Romans 1:18; Ephesians 5:6"

[[sections]]
text = "and bond slaves of Satan,"
verses = "2 Timothy 2:26"

[[sections]]
text = "and made liable to all miseries and punishments in the world and that which is to come."
verses = "Genesis 2:17; Romans 6:23; Matthew 25:41-46; Jude 7"
