id = "29"
question = "What are the punishments for sin in this world?"

[[sections]]
text = "The punishments of sin in this world are both internal and external. Internal punishments for sin in this world include blindness of mind,"
verses = "Ephesians 4:18"

[[sections]]
text = "a reprobate sense,"
verses = "Romans 1:28"

[[sections]]
text = "strong delusions,"
verses = "2 Thessalonians 2:11"

[[sections]]
text = "hardness of heart,"
verses = "Romans 2:5"

[[sections]]
text = "horror of conscience,"
verses = "Isaiah 33:14; Genesis 4:13; Matthew 27:4"

[[sections]]
text = "and vile affections."
verses = "Romans 1:26"

[[sections]]
text = "External punishments for sin in this world include God's curse on the whole creation for our sakes,"
verses = "Genesis 3:17"

[[sections]]
text = "and all other evils that befall us in our bodies, our reputations, estates, relationships, and employments,"
verses = "Deuteronomy 28:16-68"

[[sections]]
text = "including death itself."
verses = "Romans 6:21, 23"