id = "30"
question = "What are the punishments for sin in the world to come?"

[[sections]]
text = "The punishments for sin in the world to come include everlasting separation from the comfortable presence of God"
verses = "2 Thessalonians 1:9; Luke 16:24-26; John 3:36"

[[sections]]
text = "and the most grievous torments in soul and body in hellfire, without interruption, forever."
verses = "Mark 9:43-48; Matthew 25:41, 46; Revelation 14:11"
