id = "31"
question = "Does God leave all mankind to perish in the estate of sin and misery?"

[[sections]]
text = "God does not leave all men to perish in the estate of sin and misery,"
verses = "1 Thessalonians 5:9; 2 Thessalonians 2:13-14"

[[sections]]
text = "into which they fell by breach of the first covenant (commonly called the Covenant of Works)."
verses = "Genesis 3:17; Romans 5:12, 15; Hosea 6:7"

[[sections]]
text = "But God, out of His mere good pleasure, from all eternity, having chosen a people to everlasting life, did enter into a second covenant (commonly called the Covenant of Grace)"
verses = "Titus 3:4-7; Romans 3:20-22; Acts 13:48; Ephesians 1:4-5"

[[sections]]
text = "to deliver them out of the estate of sin and misery and to bring them into an estate of salvation by a Redeemer."
verses = "Galatians 3:16; Romans 5:15-21; Isaiah 53:10-11; Isaiah 59:20-21"