id = "32"
question = "How is the grace of God manifested in the Covenant of Grace?"

[[sections]]
text = "The grace of God is manifested in the Covenant of Grace by God freely providing and offering to sinners a Mediator,"
verses = "Genesis 3:15; 1 Timothy 2:5; John 3:16; John 6:27"

[[sections]]
text = "and life and salvation through Him."
verses = "1 John 5:11-12"

[[sections]]
text = "God requires faith as the only condition for sinners to become united to Him,"
verses = "John 3:16, 36; John 1:12"

[[sections]]
text = "promising and giving His Holy Spirit"
verses = "Isaiah 59:21; Luke 11:13; John 14:16-20; 1 Corinthians 12:13; Romans 8:4, 9, 11, 14-16"

[[sections]]
text = "to all His elect to work in them that faith"
verses = "2 Corinthians 4:13; Ephesians 2:8-10; Acts 16:14; 2 Peter 1:1"

[[sections]]
text = "(along with all other saving graces"
verses = "Galatians 5:22-23"

[[sections]]
text = ") and enabling them unto all holy obedience,"
verses = "Ezekiel 36:27; Ephesians 2:10"

[[sections]]
text = "as the evidence of their faith and thankfulness to God."
verses = "James 2:18, 22; 2 Corinthians 5:14-15"

[[sections]]
text = "This is the way which He has appointed and established them to salvation."
verses = "Ephesians 2:10"