id = "33"
question = "How was the Covenant of Grace revealed through the Scriptures?"

[[sections]]
text = "The Covenant of Grace is revealed in the gospel and is founded upon that eternal covenant transaction between the Father and the Son concerning the redemption of the elect"
verses = "2 Timothy 1:9; Titus 1:2; Romans 8:28-30; Ephesians 1:3-13"

[[sections]]
text = "(commonly called the Covenant of Redemption). It is first revealed to Adam in the promise of salvation by the seed of the woman"
verses = "Genesis 3:15"

[[sections]]
text = ", and is progressively revealed throughout the Old Covenant (which is defined by the Abrahamic, conditioned by the Mosaic, and focused by the Davidic covenants) until the full discovery was completed in the New Testament."
verses = "Hebrews 1:1; Hebrews 8:6-13; Hebrews 11:6,13"