id = "34"
question = "How does the Covenant of Grace differ from the Old Covenant?"

[[sections]]
text = "The Old Covenant differs from the Covenant of Grace not merely in administration, but also in substance."
verses = "2 Corinthians 3:6-9; Hebrews 8:7-13"

[[sections]]
text = "The Old Covenant was established on a temporary priesthood"
verses = "Hebrews 5:1-4; Hebrews 7:11, 23"

[[sections]]
text = "with the blood of bulls and goats (which could not remove sins"
verses = "Hebrews 10:1-4; Leviticus 1-7; Hebrews 9:18-19"

[[sections]]
text = ") and contained national, temporal promises."
verses = "Genesis 15:18; Genesis 17:8; Genesis 12:6-7; Genesis 13:14-17; Genesis 15:5"

[[sections]]
text = "The Covenant of Grace was founded on an eternal priesthood"
verses = "Hebrews 7:24; Hebrews 8:1, 6; Hebrews 9:11-15"

[[sections]]
text = "with the very blood of the Redeemer as the single, complete sacrifice for sins"
verses = "Hebrews 10:10, 14"

[[sections]]
text = "and contains the promise of eternal salvation."
verses = "Galatians 3:7-14; Hebrews 9:11-12"

[[sections]]
text = "The Old Covenant was administered by circumcision,"
verses = "Romans 4:11; Genesis 17:9-14"

[[sections]]
text = "the Passover,"
verses = "1 Corinthians 5:7; Exodus 12:14, 17, 24"

[[sections]]
text = "and other ordinances, whereas the Covenant of Grace is administered by the faithful preaching of the Word"
verses = "Luke 24:47-48; Matthew 28:19-20"

[[sections]]
text = "and the faithful administration of the sacraments of baptism"
verses = "Matthew 28:19-20"

[[sections]]
text = "and the Lord's Supper."
verses = "Matthew 26:28; 1 Corinthians 11:23-25"
