id = "35"
question = "How is the Old Covenant related to the Covenant of Grace?"

[[sections]]
text = "The Old Covenant is historically and typologically related to the Covenant of Grace. Historically, the Old Covenant promised that the nations would be blessed through Abraham;"
verses = "Genesis 12:1-3; Genesis 18:18-19; Genesis 22:17-18"

[[sections]]
text = "that the Messiah would be the physical seed of Abraham;"
verses = "Luke 1:54-55, 72-73; Galatians 3:16"

[[sections]]
text = "and that the Messiah would be an everlasting king over His people."
verses = "Isaiah 9:6-7; Jeremiah 23:5-6; Revelation 19:15-16"

[[sections]]
text = "Moreover, the Old Covenant progressively revealed the covenant of grace through types and shadows,"
verses = "Hebrews 8:5; Colossians 2:16-17; Hebrews 9:9-12, 24; Hebrews 10:1"

[[sections]]
text = "which pointed to Christ and the Covenant of Grace."
verses = "Galatians 4:21-31; Romans 9-11; Acts 26:23-24; Hebrews 8:5-13; Hebrews 9:15-24"

[[sections]]
text = "Yet, it is only by the Covenant of Grace that all descendants of Adam that ever were saved did obtain eternal life"
verses = "Hebrews 11:6, 13; Romans 4; Acts 4:12; John 8:56"

[[sections]]
text = "– for the Old Covenant imprisoned everything under sin in order that the only means to obtain the promised inheritance was through faith in Christ."
verses = "Galatians 3:19-22; 2 Corinthians 3:6-9; Romans 8:3; Romans 10:4"