id = "36"
question = "Who is the Redeemer of God's elect?"

[[sections]]
text = "The only Redeemer of God's elect (and the only Mediator of the Covenant of Grace) is the Lord Jesus Christ,"
verses = "1 Timothy 2:5; John 14:6; Acts 4:12"

[[sections]]
text = "who is the eternal Son of God, of one substance and equal with the Father."
verses = "John 1:1, 14, 18; John 10:30; Philippians 2:6; Psalm 2:7; Matthew 3:17; Matthew 17:5"

[[sections]]
text = "In the fullness of time, He became man,"
verses = "Galatians 4:4; Matthew 1:23; John 1:14"

[[sections]]
text = "and so He was and continues to be God and man with two complete and distinct natures within one person, forever."
verses = "Luke 1:35; Acts 1:11; Romans 9:5; Colossians 2:9; Hebrews 7:24-25; Hebrews 13:8; Philippians 2:5-11"