id = "37"
question = "How did Christ, being the Son of God, become man?"

[[sections]]
text = "Christ, the Son of God, became man by taking to Himself a true body and a reasonable soul."
verses = "John 1:14; Matthew 26:38; Philippians 2:7; Hebrews 2:14-17; Luke 2:40, 52; John 11:33"

[[sections]]
text = "He was conceived by the power of the Holy Spirit in the womb of the virgin Mary, of her substance and born of her,"
verses = "Luke 1:27, 31, 35; Galatians 4:4"

[[sections]]
text = "yet without sin."
verses = "Hebrews 4:15; Hebrews 7:26; 2 Corinthians 5:21; 1 John 3:5"
