id = "38"
question = "Why was it necessary that the Mediator should be God?"

[[sections]]
text = "It was necessary that the Mediator should be God so that He might sustain and keep His human nature from collapsing under the infinite wrath of God and the power of death;"
verses = "Acts 2:24-25; Romans 1:4; Romans 4:25; Hebrews 9:14"

[[sections]]
text = "give worth and efficacy to His sufferings, obedience, and intercession;"
verses = "Acts 20:28; Hebrews 9:14; Hebrews 7:25-28; John 17"

[[sections]]
text = "and to satisfy God's justice,"
verses = "Romans 3:24-26"

[[sections]]
text = "procure God's favor,"
verses = "Ephesians 1:6; Matthew 3:17"

[[sections]]
text = "purchase His very own people,"
verses = "Titus 2:13-14"

[[sections]]
text = "give His Spirit to them,"
verses = "Galatians 4:6; John 15:26; John 16:7; John 14:26"

[[sections]]
text = "conquer all their enemies,"
verses = "Luke 1:68-74"

[[sections]]
text = "and bring them to everlasting salvation."
verses = "Hebrews 5:8-9; Hebrews 9:11-15"