id = "39"
question = "Why was it necessary that the Mediator should be man?"

[[sections]]
text = "It was necessary that the Mediator should be man so that He might advance our nature,"
verses = "Hebrews 2:16; 2 Peter 1:4"

[[sections]]
text = "perform obedience to the Law,"
verses = "Galatians 4:4; Matthew 5:17; Romans 5:19; Philippians 2:8"

[[sections]]
text = "suffer and make intercession for us in our nature,"
verses = "Hebrews 2:14; Hebrews 7:24-25"

[[sections]]
text = "have a fellow feeling of our infirmities;"
verses = "Hebrews 4:15"

[[sections]]
text = "and so that we might receive the adoption of sons,"
verses = "Galatians 4:5"

[[sections]]
text = "and have comfort and access with boldness unto the throne of grace."
verses = "Hebrews 4:16"