id = "40"
question = "Why was it necessary that the Mediator should be God and man in one person?"

[[sections]]
text = "It was necessary that the Mediator, who was to reconcile God and man, should Himself be both God and man in one person, so that the proper works of each nature might be accepted of God on our behalf,"
verses = "Matthew 1:21, 23; Matthew 3:17; Hebrews 9:14"

[[sections]]
text = "and relied on by us as the works of the whole person."
verses = "1 Peter 2:6"