id = "41"
question = "Why was our Redeemer called Jesus Christ?"

[[sections]]
text = "Our Redeemer was called Jesus Christ because He saves His people from their sins"
verses = "Matthew 1:21"

[[sections]]
text = "and because He was anointed with the Holy Spirit above measure."
verses = "Matthew 3:16; Acts 10:37-38; John 3:34; Psalm 45:7"

[[sections]]
text = "Consequently, He was set apart and fully equipped with all authority and power"
verses = "John 6:27; Matthew 28:18-20; Romans 1:3-4"

[[sections]]
text = "to execute His offices within the Church."
verses = ""
