id = "42"
question = "What offices does Christ execute as our Redeemer?"

[[sections]]
text = "Christ executes the offices of a prophet,"
verses = "Acts 3:21-22; Luke 4:18-21; Hebrews 1:1-2; Deuteronomy 18:18"

[[sections]]
text = "of a priest,"
verses = "Hebrews 5:5-7; Hebrews 4:14-15"

[[sections]]
text = "and of a king of His church,"
verses = "Psalm 2:6; Luke 1:32-34; John 18:37; Matthew 21:5; Isaiah 9:6-7; Philippians 2:8-11"

[[sections]]
text = "both in His estate of humiliation and exaltation."
verses = ""