id = "43"
question = "How does Christ execute the office of a prophet?"

[[sections]]
text = "Christ executes the office of a prophet by revealing to the Church,"
verses = "John 15:15; John 1:18"

[[sections]]
text = "in various ways"
verses = "Hebrews 1:1-2"

[[sections]]
text = "throughout all ages by His Spirit and Word,"
verses = "1 Peter 1:10-12"

[[sections]]
text = "the complete will of God for their edification and salvation."
verses = "Acts 20:32; Ephesians 4:11-13; John 20:31"