id = "44"
question = "How does Christ execute the office of a priest?"

[[sections]]
text = "Christ executes the office of a priest by offering Himself once for all as a sacrifice without spot to God"
verses = "Hebrews 9:14, 28; Hebrews 10:12; Isaiah 53"

[[sections]]
text = "to satisfy divine justice and to be reconciliation for the sins of His people;"
verses = "Hebrews 2:17; 2 Corinthians 5:18; Colossians 1:21-22"

[[sections]]
text = "and in making continual intercession for His people."
verses = "Hebrews 7:25; Hebrews 9:24"
