id = "45"
question = "How does Christ make intercession?"

[[sections]]
text = "Christ makes intercession by continually appearing in our human nature before the Father in heaven,"
verses = "Hebrews 9:12, 24"

[[sections]]
text = "in the merit of His obedience and sacrifice on earth,"
verses = "Isaiah 53:12; Hebrews 1:3"

[[sections]]
text = "declaring His will to be applied to all believers,"
verses = "John 3:16; John 17:9, 20, 24"

[[sections]]
text = "answering all accusations against them,"
verses = "Romans 8:33-34"

[[sections]]
text = "and procuring for them peace of conscience, in spite of their daily failures,"
verses = "Romans 5:1-2; 1 John 2:1-2"

[[sections]]
text = "access with boldness to the throne of grace,"
verses = "Hebrews 4:16"

[[sections]]
text = "and full acceptance of their persons and services."
verses = "Ephesians 1:6; 1 Peter 2:5"