id = "46"
question = "How does Christ execute the office of a king?"

[[sections]]
text = "Christ executes the office of a king by calling a people for Himself out of the world"
verses = "Acts 15:14-16; Genesis 49:10; Psalm 110:3; John 17:2"

[[sections]]
text = "and giving them officers,"
verses = "Ephesians 4:11-12; 1 Corinthians 12:28"

[[sections]]
text = "laws,"
verses = "Isaiah 33:22"

[[sections]]
text = "and censures by which He visibly governs them."
verses = "Matthew 18:17-18; 1 Corinthians 5:4-5"

[[sections]]
text = "He bestows saving grace upon His elect,"
verses = "Acts 5:31"

[[sections]]
text = "rewards their obedience,"
verses = "Revelation 22:12; Revelation 2:10"

[[sections]]
text = "corrects them for their sins,"
verses = "Revelation 3:19"

[[sections]]
text = "preserves and supports them in all their temptations and sufferings,"
verses = "Isaiah 63:9"

[[sections]]
text = "restrains and overcomes all their enemies,"
verses = "1 Corinthians 15:25; Psalm 110:1-2"

[[sections]]
text = "and powerfully orders everything for His own glory and their well-being."
verses = "Romans 14:10-11; Romans 8:28"

[[sections]]
text = "Finally, Christ executes just retribution against all others who neither know God nor obey the gospel."
verses = "2 Thessalonians 1:8-9; Psalm 2:8-9"
