id = "47"
question = "What was the estate of Christ's humiliation?"

[[sections]]
text = "The estate of Christ's humiliation was that low condition wherein He, for our sakes, emptied Himself of His glory by taking upon Himself the form of a servant"
verses = "Philippians 2:6-8"

[[sections]]
text = "in His conception"
verses = "Luke 1:31"

[[sections]]
text = "and birth,"
verses = "Luke 2:7"

[[sections]]
text = "life,"
verses = "Galatians 4:4; 2 Corinthians 8:9; Luke 9:58; Hebrews 2:18; Isaiah 52:3"

[[sections]]
text = "death,"
verses = "Psalm 22:1; Matthew 27:46; Isaiah 53:10; 1 John 2:2"

[[sections]]
text = "and after His death until His resurrection."
verses = "Matthew 12:40; 1 Corinthians 15:3-4; Acts 2:24-31"