id = "48"
question = "How did Christ humble Himself in His conception and birth?"

[[sections]]
text = "Christ humbled Himself in His conception and birth in that, being from all eternity the Son of God in the bosom of the Father, it pleased Him in the fullness of time to become the son of man, born of a woman of low estate and into conditions that were even worse than ordinary."
verses = "John 1:14,18; Galatians 4:4; Luke 2:7; Philippians 2:6-8; 2 Corinthians 8:9"
