id = "49"
question = "How did Christ humble Himself in His life?"

[[sections]]
text = "Christ humbled Himself in His life by subjecting Himself to the Law,"
verses = "Galatians 4:4"

[[sections]]
text = "which He perfectly fulfilled,"
verses = "Matthew 5:17; Romans 5:19"

[[sections]]
text = "and by struggling with the disgraces of this world,"
verses = "Psalm 22:6; Isaiah 53:2-3; Hebrews 12:2-3"

[[sections]]
text = "the temptations of Satan,"
verses = "Matthew 4:1-11; Luke 4:13"

[[sections]]
text = "and the frailty of His body, whether common to the nature of man or particularly associated with His low condition."
verses = "Hebrews 2:17-18; Hebrews 4:15; Isaiah 52:13-14"
