id = "50"
question = "How did Christ humble Himself in His death?"

[[sections]]
text = "Christ humbled Himself in His death by being betrayed by Judas,"
verses = "Matthew 27:4"

[[sections]]
text = "forsaken by His disciples,"
verses = "Matthew 26:56"

[[sections]]
text = "scorned and rejected by the world,"
verses = "Isaiah 53:2-3"

[[sections]]
text = "condemned by Pilate, and tormented by His persecutors."
verses = "Matthew 27:26-50; John 19:34; Luke 22:63-64"

[[sections]]
text = "He struggled with the terrors of death and the powers of darkness, felt and bore the weight of God's wrath."
verses = "Luke 22:44; Matthew 27:46"

[[sections]]
text = "Finally, enduring the painful, shameful, and cursed death on the cross"
verses = "Philippians 2:8; Hebrews 12:2; Galatians 3:13"

[[sections]]
text = "He laid down His life as an offering for sin."
verses = "Isaiah 53:10; Mark 10:45"