id = "51"
question = "How did Christ humble Himself after His death?"

[[sections]]
text = "Christ's humiliation after His death involved His being buried,"
verses = "1 Corinthians 15:3-4"

[[sections]]
text = "and continuing in the state of the dead and under the power of death until the third day,"
verses = "Acts 2:24-31; Romans 6:9; Matthew 12:40"

[[sections]]
text = "which has been otherwise expressed in these words in the Apostles' creed: He descended into hell."
verses = ""
