id = "52"
question = "What was the estate of Christ's exaltation?"

[[sections]]
text = "The estate of Christ's exaltation consists of His resurrection,"
verses = "1 Corinthians 15:3-4"

[[sections]]
text = "His ascension,"
verses = "Psalm 68:18; Acts 1:11; Ephesians 4:8"

[[sections]]
text = "His sitting at the right hand of the Father,"
verses = "Ephesians 1:20; Psalm 110:1; Acts 2:33-34; Hebrews 1:3"

[[sections]]
text = "and His imminent return to judge the world."
verses = "Acts 1:11; Acts 17:31; Matthew 16:27"