id = "53"
question = "How was Christ exalted in His resurrection?"

[[sections]]
text = "Christ was exalted in His resurrection, in that, not having seen corruption in death (for it was impossible for Him to be held"
verses = "Acts 2:24-27"

[[sections]]
text = ") and having the very same body in which He suffered with all its essential properties thereof"
verses = "Luke 24:39"

[[sections]]
text = "truly united to His soul,"
verses = "Romans 6:9; Revelation 1:18"

[[sections]]
text = "(but without mortality and other common infirmities associated with this life) He rose again from the dead on the third day by His own power."
verses = "John 10:18"

[[sections]]
text = "By His resurrection, He plainly declared Himself to be the Son of God,"
verses = "Romans 1:4"

[[sections]]
text = "to have satisfied divine justice,"
verses = "Romans 8:34; Romans 3:25-26; Hebrews 9:13-14"

[[sections]]
text = "to have conquered death as well as Him who holds the power of death,"
verses = "Hebrews 2:14"

[[sections]]
text = "and to be Lord of the living and the dead."
verses = "Romans 14:9"

[[sections]]
text = "He did all this as a public person"
verses = "1 Corinthians 15:21-22; Isaiah 53:10-11"

[[sections]]
text = "and as the head of His church"
verses = "Ephesians 1:20-23; Colossians 1:18"

[[sections]]
text = "in order to justify believers,"
verses = "Romans 4:25"

[[sections]]
text = "make them alive in His grace,"
verses = "Ephesians 2:1-6; Colossians 2:12"

[[sections]]
text = "support them against their enemies,"
verses = "1 Corinthians 15:25-27; Psalm 2:7-9"

[[sections]]
text = "and to assure them of their resurrection from the dead at the last day."
verses = "1 Corinthians 15:20; 1 Thessalonians 4:14"
