id = "54"
question = "How was Christ exalted in His ascension?"

[[sections]]
text = "Christ was exalted in His ascension, in that, having after His resurrection appeared numerous times and conversed with His apostles, speaking to them of the things pertaining to the kingdom of God,"
verses = "Acts 1:2-3"

[[sections]]
text = "and commissioning them to preach the gospel to all nations,"
verses = "Matthew 28:19-20"

[[sections]]
text = "He, in our nature and as our head,"
verses = "John 20:17; Hebrews 6:20"

[[sections]]
text = "visibly ascended to the highest heavens forty days after His resurrection, triumphing over enemies."
verses = "Ephesians 4:8"

[[sections]]
text = "There, He receives gifts for men,"
verses = "Acts 1:9-11; Ephesians 4:7-8; Psalm 68:18; Ephesians 4:10; Acts 2:33"

[[sections]]
text = "raises our minds and affections,"
verses = "Colossians 3:1-2"

[[sections]]
text = "and prepares a place for us,"
verses = "John 14:3"

[[sections]]
text = "where He is and shall continue to be until His second coming at the end of the world."
verses = "Acts 3:21"
