id = "55"
question = "How is Christ exalted in His sitting at the right hand of the Father?"

[[sections]]
text = "Christ is exalted in His sitting at the right hand of Father, in that, as the God-man, He is advanced to the highest favor with God the Father"
verses = "Philippians 2:9"

[[sections]]
text = "with all fullness of joy,"
verses = "Acts 2:28; Psalm 16:11"

[[sections]]
text = "glory,"
verses = "John 17:5"

[[sections]]
text = "and power over all things in heaven and earth."
verses = "Daniel 7:13-14; Ephesians 1:22; 1 Peter 3:22"

[[sections]]
text = "There, Christ gathers and defends His church, subdues their enemies; provides His ministers and people with gifts and graces,"
verses = "Ephesians 4:10-12; Psalm 110:1; Hebrews 10:12-14; Ezekiel 37:24"

[[sections]]
text = "and makes intercession for them."
verses = "Romans 8:34; 1 John 2:1; Hebrews 7:25"
