id = "56"
question = "How is Christ to be exalted in His imminent return to judge the world?"

[[sections]]
text = "Christ is to be exalted in His imminent return to judge the world, in that He, who was unjustly judged and condemned by wicked men,"
verses = "Acts 3:14-15"

[[sections]]
text = "shall come again at the last day in great power"
verses = "Matthew 24:30; 2 Thessalonians 1:9-10"

[[sections]]
text = "and in the full manifestation of His own and His Father's glory with all His holy angels,"
verses = "Luke 9:26; Matthew 25:31"

[[sections]]
text = "accompanied by a shout of command, the voice of the archangel and the trumpet of God,"
verses = "1 Thessalonians 4:16"

[[sections]]
text = "to judge the world in righteousness."
verses = "Acts 17:30-31; 2 Thessalonians 1:6-8"
