id = "57"
question = "What benefits has Christ procured by His mediation?"

[[sections]]
text = "Christ, by His mediation, has procured redemption"
verses = "1 Timothy 2:5-6; Hebrews 9:12; Ephesians 1:7"

[[sections]]
text = "with all the other benefits of the covenant of grace."
verses = "2 Corinthians 1:20; Ephesians 1:3-6; 2 Peter 1:3-4"