id = "58"
question = "Who are made partakers of redemption through Christ?"

[[sections]]
text = "Redemption is certainly applied and effectually communicated to all those for whom Christ has purchased it"
verses = "Ephesians 1:13-14; John 6:37-39; John 10:15-16"

[[sections]]
text = "through the Holy Spirit"
verses = "Titus 3:5-6; John 3:5-6; John 1:11-13"

[[sections]]
text = "who, in the process of time, works faith in them to believe in Christ as presented in the gospel,"
verses = "Romans 10:17; John 6:37,39; John 10:15-16; 1 Corinthians 2:12-16; Romans 8:29-30"

[[sections]]
text = "and thereby unites them, spiritually and mystically yet truly and inseparably, to Christ as their head and husband."
verses = "1 Corinthians 6:17; John 10:28; John 15:1-5; Ephesians 5:23, 30"

[[sections]]
text = "This union with Christ is done in their effectual calling."
verses = "1 Peter 5:10; 1 Corinthians 1:9; Ephesians 2:8; Ephesians 3:17"