id = "59"
question = "What is effectual calling?"

[[sections]]
text = "Effectual calling is the work of God's almighty power and grace,"
verses = "Ezekiel 37:9-14; John 5:25; Ephesians 1:18-20; 2 Timothy 1:8-9"

[[sections]]
text = "whereby He (out of His free and special love to His elect and not from anything inherently in them"
verses = "Titus 3:4-5; Ephesians 2:4-9; Romans 9:11; Deuteronomy 9:5"

[[sections]]
text = ") at the right time invites and draws them to Jesus Christ by His Word and Spirit."
verses = "John 3:5; Titus 3:5; 2 Corinthians 5:20; 2 Corinthians 6:1-2; John 6:44-45; Acts 16:14; 2 Thessalonians 2:13-14"

[[sections]]
text = "God savingly enlightens their minds in the knowledge of Christ,"
verses = "Acts 26:18; 1 Corinthians 2:10-12; 2 Corinthians 4:6; Ephesians 1:17-18"

[[sections]]
text = "renews and transforms their wills,"
verses = "Ezekiel 11:19; Ezekiel 36:26-27; John 6:45"

[[sections]]
text = "and makes them (even though they are dead in sin) willing and freely able to answer His call voluntarily and to gladly accept the grace offered and conveyed."
verses = "Ephesians 2:5; Philippians 2:13; Deuteronomy 30:6; Isaiah 45:22; Matthew 11:28-30; Revelation 22:17"