id = "60"
question = "Are the elect only effectually called?"

[[sections]]
text = "All the elect, and only they, are effectually called."
verses = "Acts 13:48"

[[sections]]
text = "Although others may be and often are externally called by the ministry of the Word,"
verses = "Matthew 22:14; Acts 8:13-21"

[[sections]]
text = "and although the Spirit may work in them in some of the same ways He works in the elect,"
verses = "Matthew 7:22; Matthew 13:20-21; Hebrews 6:4-6"

[[sections]]
text = "from their own willful neglect of and contempt for the grace offered to them, they are justly allowed to remain in their unbelief and never truly come to Christ."
verses = "John 12:38-40; Acts 28:25-27; John 6:64-65; Psalm 81:11-12; Hebrews 10:29; 1 John 2:19"
