id = "61"
question = "Can those who have never heard the gospel and so neither know Jesus Christ nor believe in Him be saved by living according to their own natural understanding?"

[[sections]]
text = "Those who have never heard the gospel"
verses = "Romans 10:14"

[[sections]]
text = "and do not know Jesus Christ"
verses = "2 Thessalonians 1:8-9; Ephesians 2:12; John 1:10-12"

[[sections]]
text = "nor believe in Him cannot be saved"
verses = "John 8:24; Mark 16:16; Acts 4:12; Romans 1:18-32"

[[sections]]
text = "no matter how diligently they frame their lives according to their own natural understanding"
verses = "1 Corinthians 1:20-24; Romans 1:18-32; Romans 3:9-19"

[[sections]]
text = "or the laws of that religion which they profess."
verses = "John 4:22; Romans 9:31-32; Philippians 3:4-10"

[[sections]]
text = "Salvation comes from no other than Christ alone."
verses = "Acts 4:12"