id = "62"
question = "What benefits do the elect experience through Christ in this life?"

[[sections]]
text = "The elect experience union and communion with Him in grace and glory"
verses = "John 17:21; Ephesians 2:5-6; John 17:24; 1 John 1:3; John 1:16; Ephesians 3:16-19; Philippians 3:10"

[[sections]]
text = "and thus, partake of the power of His mediation in their justification,"
verses = "Romans 8:30"

[[sections]]
text = "adoption,"
verses = "Ephesians 1:5"

[[sections]]
text = "sanctification, and whatever else, in this life, manifests their union with Him."
verses = "1 Corinthians 1:30; 1 Corinthians 6:11"