id = "63"
question = "What is justification?"

[[sections]]
text = "Justification is the act of God's free grace unto sinners,"
verses = "Romans 3:22-25"

[[sections]]
text = "by which He pardons all their sins and accepts them as righteous in His sight;"
verses = "Jeremiah 23:6; Romans 4:6-8; 2 Corinthians 5:19-21; Romans 3:22-28"

[[sections]]
text = "not because of anything worked in them or done by them"
verses = "Titus 3:5-7; Ephesians 1:7"

[[sections]]
text = "but because God imputes to them Christ's active obedience unto the whole law,"
verses = "Romans 10:4; Romans 5:10, 19; Matthew 3:15"

[[sections]]
text = "and passive obedience in His death for their whole and sole righteousness"
verses = "Romans 3:25; Romans 5:9; Hebrews 10:11-14; 2 Corinthians 5:21"

[[sections]]
text = "which can only be appropriated by faith."
verses = "Acts 10:43; Galatians 2:16; Philippians 3:9"
