id = "64"
question = "How is justification an act of God's free grace?"

[[sections]]
text = "By His obedience and death Christ made the proper, real, and full satisfaction to God's justice on behalf of those who are justified."
verses = "Romans 5:8-19"

[[sections]]
text = "Yet, insofar as this satisfaction is accepted by God as a guarantee of performance, which He might have demanded from the justified, and since God Himself provided a guarantor in the person of His only Son,"
verses = "1 Timothy 2:5-6; Hebrews 10:10; Matthew 20:28; Isaiah 53:4-12; Romans 8:32; 1 Peter 1:18-19"

[[sections]]
text = "in justification God imputes righteousness to the justified"
verses = "2 Corinthians 5:21; Romans 4:6-11"

[[sections]]
text = "and requires nothing from them in return except faith,"
verses = "Romans 3:24-25"

[[sections]]
text = "which they also have as a gift from Him."
verses = "Ephesians 2:8"

[[sections]]
text = "Consequently, justification comes to the justified as an act of God's free grace."
verses = "Ephesians 1:7; Romans 3:24-25"
