id = "65"
question = "What is justifying faith?"

[[sections]]
text = "Justifying faith is an act of the free grace of God"
verses = "Hebrews 10:39"

[[sections]]
text = "wrought in the hearts of sinners by the Spirit"
verses = "2 Corinthians 4:13; Ephesians 1:17-19; 1 Corinthians 12:3; 1 Peter 1:2"

[[sections]]
text = "and the Word of God."
verses = "Romans 10:14-17; 1 Corinthians 1:21"

[[sections]]
text = "By this faith, sinners are convinced of their sinfulness and miserable condition and of their inability in themselves (and all other creatures) to recover out of their lost condition,"
verses = "Acts 2:37; Acts 16:30; John 16:8-9; Romans 6:6; Ephesians 2:1; Acts 4:12"

[[sections]]
text = "and by this faith, they give full assent to the truth of the gospel promise."
verses = "Ephesians 1:13; Hebrews 11:13"

[[sections]]
text = "They receive and rest on Christ and His righteousness for pardon of sin,"
verses = "John 1:12; Acts 16:31; Acts 10:43; Zechariah 3:8-9"

[[sections]]
text = "as held forth in the gospel, and for being accepted and accounted as righteous in the sight of God for salvation."
verses = "Philippians 3:9; Acts 15:11"