id = "66"
question = "How does faith justify a sinner in the sight of God?"

[[sections]]
text = "Faith justifies a sinner in the sight of God only as an instrument by which the sinner receives Christ and applies Christ's righteousness,"
verses = "John 1:12; Philippians 3:9; Galatians 2:16"

[[sections]]
text = "not because of any other grace that accompanies faith or because of any good works that result from faith."
verses = "Galatians 3:11; Romans 3:28"

[[sections]]
text = "Nor is it the case that the grace of faith or any action springing from it is imputed to the sinner for His justification."
verses = "Romans 4:5; Romans 10:10"