id = "67"
question = "What is adoption?"

[[sections]]
text = "Adoption is an act of the free grace of God"
verses = "1 John 3:1"

[[sections]]
text = "in and for His only Son Jesus Christ,"
verses = "Ephesians 1:5; Galatians 4:4-5"

[[sections]]
text = "by which all those who are justified are received into the number of His children,"
verses = "John 1:12; Romans 8:15-16"

[[sections]]
text = "have His name put upon them,"
verses = "Numbers 6:24-27; 2 Corinthians 6:18; Revelation 3:12"

[[sections]]
text = "have the Spirit of His Son given to them,"
verses = "Galatians 4:6"

[[sections]]
text = "are under His fatherly care,"
verses = "Psalm 103:13; Matthew 6:32; Hebrews 12:5-11"

[[sections]]
text = "are welcomed to all the liberties and privileges of the sons of God, and are made heirs of all the promises and fellow-heirs with Christ in glory."
verses = "Hebrews 6:12; Romans 8:17; 1 Peter 1:3-4"