id = "68"
question = "What is sanctification?"

[[sections]]
text = "Sanctification is a work of God's free grace for those whom God has chosen to be holy before the foundation of the world and to whom, in the process of time, the powerful operation of the Spirit"
verses = "Ezekiel 36:27; Philippians 2:13; 2 Thessalonians 2:13; Ephesians 1:4; 1 Corinthians 6:11"

[[sections]]
text = "applies the death and resurrection of Christ."
verses = "Romans 6:4-6; Colossians 3:1-3; Philippians 3:10"

[[sections]]
text = "They are thus renewed in their whole man after the image of God,"
verses = "2 Corinthians 5:17; Ephesians 4:23-24; 1 Thessalonians 5:23"

[[sections]]
text = "have the seeds of repentance unto life and all the other saving graces put into their hearts"
verses = "Acts 11:18; 1 John 3:9"

[[sections]]
text = "and these graces are so aroused, increased, and strengthened"
verses = "Jude 20; Hebrews 6:11-12; Ephesians 3:16-19; Colossians 1:10-11"

[[sections]]
text = "that they progressively put sin to death and rise unto newness of life."
verses = "Ezekiel 36:25-27; Romans 6:4-14; 2 Corinthians 7:1; 1 Peter 2:24; Galatians 5:24"
