id = "69"
question = "What is repentance unto life?"

[[sections]]
text = "Repentance unto life is an act of God's free grace"
verses = "2 Timothy 2:25; Acts 11:18"

[[sections]]
text = "wrought in the heart of a sinner by the Spirit"
verses = "Zechariah 12:10"

[[sections]]
text = "and the Word of God."
verses = "Acts 11:18-21"

[[sections]]
text = "By it, sinners recognize not only the danger of their sins"
verses = "Ezekiel 18:28-32; Luke 15:17-18; Hosea 2:6-7"

[[sections]]
text = "but also the filthiness and repulsiveness of their sins to God."
verses = "Ezekiel 36:31; Isaiah 30:22; Philippians 3:7-8"

[[sections]]
text = "Understanding that in Christ, God is merciful to those who repent,"
verses = "Joel 2:12-13; Psalm 51:1-4; Luke 15:7-10; Acts 2:37"

[[sections]]
text = "sinners suffer such deep sorrow for"
verses = "Jeremiah 31:18-19; Psalm 32:5"

[[sections]]
text = "and hate their sins"
verses = "2 Corinthians 7:11"

[[sections]]
text = "so much that they turn away from all of them and turn to God,"
verses = "Luke 1:16-17; 1 Thessalonians 1:9; Acts 26:18; Ezekiel 14:6; 1 Kings 8:47-48"

[[sections]]
text = "purposing to walk continually with Him according to this new obedience in every way."
verses = "2 Chronicles 7:14; Psalm 119:57-64; Matthew 3:8; 2 Corinthians 7:10"