id = "70"
question = "What is the difference between justification and sanctification?"

[[sections]]
text = "Although sanctification is inseparably joined with justification,"
verses = "1 Corinthians 6:11; 1 Corinthians 1:30"

[[sections]]
text = "the two are distinctly different. In justification God imputes the righteousness of Christ to believers"
verses = "Romans 4:6-8"

[[sections]]
text = "whereas in sanctification, His Spirit infuses believers with grace, and enables them to exercise this grace."
verses = "Ezekiel 36:27; Hebrews 9:13-14"

[[sections]]
text = "In justification, sin is pardoned apart from the work of the believer;"
verses = "Romans 3:24-25"

[[sections]]
text = "whereas in sanctification, sin is subdued by Spirit-empowered effort of the believer."
verses = "Romans 6:6-14; Romans 8:13; Philippians 2:12-13"

[[sections]]
text = "Justification perfectly and equally frees all believers from the wrath of God so that they never fall into condemnation;"
verses = "Romans 8:33-34"

[[sections]]
text = "whereas sanctification is not completed in any believer in this life,"
verses = "1 John 2:12-14; Hebrews 5:12-14; 1 John 1:8-10"

[[sections]]
text = "but only grows towards perfection."
verses = "2 Corinthians 7:1; Philippians 3:12-14"
