id = "71"
question = "Why are believers not completely sanctified?"

[[sections]]
text = "Believers are not completely sanctified because they retain some remnants of sin through their whole being and are continually plagued with desires of their old sinful nature that are contrary to the Spirit. Consequently believers are frequently defeated by temptations, commit many sins,"
verses = "Romans 7:18-23; Mark 14:66-72; Galatians 2:11-12"

[[sections]]
text = "and are hindered from performing their spiritual obligations,"
verses = "Hebrews 12:1"

[[sections]]
text = "so that their best works in God's eyes are imperfect and defiled."
verses = "Isaiah 64:6; Exodus 28:38; Galatians 5:16-18"
