id = "72"
question = "What are the benefits which in this life do accompany or flow from justification, adoption, and sanctification?"

[[sections]]
text = "The benefits which in this life do accompany or flow from justification, adoption, and sanctification are the first-fruits of communion with Christ mainly in the form of interest in the glory Christ fully possesses,"
verses = "Ephesians 2:5-6"

[[sections]]
text = "and, as a down payment on this communion, the elect enjoy an assurance of God's love,"
verses = "Romans 5:5; 2 Corinthians 1:22"

[[sections]]
text = "peace of conscience, joy in the Holy Spirit, increase of grace, and hope of glory."
verses = "Romans 5:1-2; Romans 14:17; 2 Peter 3:18"