id = "73"
question = "Can true believers fall from their state of grace?"

[[sections]]
text = "True believers, because of God's unchangeable love,"
verses = "Jeremiah 31:3"

[[sections]]
text = "His decree and covenant to grant them perseverance,"
verses = "2 Timothy 2:19; Hebrews 13:20-21; 2 Samuel 23:5"

[[sections]]
text = "their inseparable union with Christ,"
verses = "1 Corinthians 1:8-9"

[[sections]]
text = "His continual intercession for them,"
verses = "Hebrews 7:25; Luke 22:32"

[[sections]]
text = "and the presence of His Spirit and seed of God abiding in them,"
verses = "1 John 3:9; 1 John 2:27"

[[sections]]
text = "can neither totally nor finally fall out of their state of grace,"
verses = "Jeremiah 32:40; John 10:28"

[[sections]]
text = "but are preserved by the power of God through faith unto salvation."
verses = "1 Peter 1:5"
