id = "74"
question = "Can true believers be infallibly assured that they will remain in a state of grace?"

[[sections]]
text = "True believers who endeavor to walk in good conscience before Him,"
verses = "1 John 2:3; Hebrews 10:19-23"

[[sections]]
text = "may, without extraordinary revelation, be infallibly assured that they are and will remain in a state of grace, persevering to salvation."
verses = "1 John 5:13; Hebrews 6:19-20; 2 Peter 1:5-11"

[[sections]]
text = "This assurance comes from faith grounded on the truth of God's promises and from the Spirit, who gives believers spiritual insight into their own hearts, to which these promises are directed."
verses = "1 Corinthians 2:12; 1 John 3:14-24; 1 John 4:13-16; Hebrews 6:11-12"

[[sections]]
text = "The Spirit also testifies with their spirits that they are the children of God."
verses = "Romans 8:15-16"