id = "75"
question = "Are all true believers at all times assured of their salvation?"

[[sections]]
text = "Since the assurance of grace and salvation is not essential to faith, true believers may have to wait long before they obtain it,"
verses = "Ephesians 1:13; Isaiah 50:10; Psalm 88:1-15"

[[sections]]
text = "and once they have obtained it, their assurance may be weakened and interrupted from being afflicted by all kinds of psychological problems, sins, temptations, and from losing the sense of God's favor."
verses = "Psalm 77:1-12; Psalm 51:8-12; Psalm 31:22; Psalm 22:1; Ephesians 4:30; Luke 22:31-34"

[[sections]]
text = "However, the Holy Spirit keeps believers from complete despair by never allowing them to be without an inner sense of His presence and support."
verses = "1 John 3:9; Isaiah 54:7-10; 1 Peter 4:12-14"
