id = "76"
question = "Shall all men die?"

[[sections]]
text = "Since death is the wages of sin,"
verses = "Romans 6:23"

[[sections]]
text = "it is appointed unto all men to die once"
verses = "Hebrews 9:27"

[[sections]]
text = "because all have sinned."
verses = "Romans 5:12"