id = "77"
question = "Since death is the wages of sin, why are the righteous not delivered from death?"

[[sections]]
text = "The righteous will be delivered from death itself at the last day. Moreover, even when they die, they are delivered from the sting and curse of death,"
verses = "1 Corinthians 15:26, 55-57; Hebrews 2:15"

[[sections]]
text = "and God's love"
verses = "Isaiah 57:1-2; 2 Kings 22:20"

[[sections]]
text = "completely frees them from sin and misery,"
verses = "Revelation 14:13; Ephesians 5:27; Luke 16:25; 2 Corinthians 5:1-8"

[[sections]]
text = "enabling them to have a deeper communion with Christ when they enter into His glory after death."
verses = "Luke 23:43; Philippians 1:23"