id = "78"
question = "What benefits do believers receive from Christ at death?"

[[sections]]
text = "The benefits that believers receive from Christ at death involves their souls being made completely holy"
verses = "Hebrews 12:23; Acts 7:55-59"

[[sections]]
text = "and being received into the highest heavens,"
verses = "2 Corinthians 5:1-8; Philippians 1:23; Acts 3:21; Ephesians 4:10; Luke 23:43"

[[sections]]
text = "which are fruits of their communion in glory with Christ. There they behold the face of God in light and glory"
verses = "1 John 3:2; 1 Corinthians 13:12"

[[sections]]
text = "as they wait for the full redemption of their bodies,"
verses = "Romans 8:23; Psalm 16:9"

[[sections]]
text = "which even in death continue united to Christ"
verses = "1 Thessalonians 4:14-16"

[[sections]]
text = "and rest in the grave as in a bed,"
verses = "Isaiah 57:2"

[[sections]]
text = "until at the last day body and soul are reunited."
verses = "Job 19:26-27"
