id = "79"
question = "What shall be done to the wicked at death?"

[[sections]]
text = "At death, the souls of the wicked shall be cast into hell, where they remain in torment and utter darkness, and their bodies lie in their graves until the resurrection and judgment of the great day."
verses = "Luke 16:22-24; Psalm 49:14"