id = "80"
question = "What must we believe about the resurrection?"

[[sections]]
text = "We must first of all believe that at the last day there is going to be a general resurrection of the dead, both of the just and unjust."
verses = "Daniel 12:2; Acts 24:15"

[[sections]]
text = "When that happens, those who are still alive on earth shall be instantly changed, and the very same bodies of the dead that were buried will be reunited with their souls and raised up by the power of Christ."
verses = "Job 19:26; 1 Corinthians 15:51-53; 1 Thessalonians 4:15-17; John 5:28-29; Romans 8:11"

[[sections]]
text = "Through the Spirit of Christ and by virtue of His resurrection, as their head, the bodies of the righteous will be raised in power, spiritual and imperishable, and made in the likeness of Christ's glorious body."
verses = "1 Corinthians 15:21-23, 42-44; Philippians 3:21"

[[sections]]
text = "Christ will raise up in dishonor the bodies of the wicked, who offend Him as judge."
verses = "John 5:27-29; Matthew 25:33"