id = "81"
question = "What shall immediately follow after the resurrection?"

[[sections]]
text = "Immediately after the resurrection shall follow the general and final judgment of angels and men,"
verses = "Ecclesiastes 12:14; 2 Peter 2:4-15; Matthew 25:46; 2 Corinthians 5:10"

[[sections]]
text = "of which no one knows the day or hour so that all may anticipate, pray for, and be ever ready for the coming of the Lord."
verses = "Matthew 24:36-44; Mark 13:35-37"