id = "82"
question = "What benefits do believers receive from Christ at the Day of Judgment?"

[[sections]]
text = "At the Day of Judgment, believers will be caught up with Christ in the clouds"
verses = "1 Thessalonians 4:17; 1 Corinthians 15:42-43"

[[sections]]
text = "and placed on His right hand, where they will be publicly acknowledged and acquitted."
verses = "Matthew 25:33; Matthew 10:32"

[[sections]]
text = "They will join Christ in the judgment of reprobate angels and men,"
verses = "1 Corinthians 6:2-3"

[[sections]]
text = "and be received into heaven."
verses = "Matthew 25:34-46"

[[sections]]
text = "There they will be completely and forever freed from all sin and misery,"
verses = "Ephesians 5:27; Revelation 14:13"

[[sections]]
text = "filled with unimaginable joy,"
verses = "Psalm 16:11"

[[sections]]
text = "and made perfectly holy and happy both in body and soul, in the vast company of each other and the holy angels."
verses = "Hebrews 12:22-23"

[[sections]]
text = "They will be particularly blessed in the visual presence and enjoyment of God the Father, the Lord Jesus Christ, and the Holy Spirit, forever."
verses = "1 John 3:2; Romans 8:29; 1 Corinthians 13:12; 1 Thessalonians 4:17-18"
