id = "83"
question = "What shall be done to the wicked at the Day of Judgment?"

[[sections]]
text = "At the Day of Judgment, the wicked will be put on Christ's left hand,"
verses = "Matthew 25:33"

[[sections]]
text = "and with the evidence against them clearly presented and fully recognized by them,"
verses = "Romans 2:15-16"

[[sections]]
text = "they will be justly and terribly condemned,"
verses = "Matthew 25:41-43"

[[sections]]
text = "after which they will be cast out from the favorable presence of God and the glorious fellowship with Christ, His saints, and His angels, and thrown into hell to be punished forever with unspeakable torments, both of body and soul, along with the devil and his angels."
verses = "Luke 16:26; 2 Thessalonians 1:8-9"