id = "84"
question = "What is the duty which God requires of man?"

[[sections]]
text = "The duty which God requires of man is obedience to His plainly and fully revealed will"
verses = "Deuteronomy 29:29; Micah 6:8; 1 John 5:2-3; Romans 12:1-2; 1 Samuel 15:22"

[[sections]]
text = "which is our reasonable service due to Him as our Creator, preserver, Master, and Sovereign."
verses = "Romans 12:1; Isaiah 44:21; Deuteronomy 32:6; Malachi 1:6; Psalm 22:27-28"