id = "85"
question = "In the beginning what did God reveal unto man as the rule of His obedience?"

[[sections]]
text = "The rule of obedience revealed to Adam in the estate of innocence, and to all mankind in him (besides a special command not to eat from the tree of the knowledge of good and evil) was the moral law."
verses = "Genesis 1:26-27; Romans 2:14-15; Romans 10:5; Genesis 2:17"