id = "86"
question = "What is the moral law?"

[[sections]]
text = "The moral law is the declaration of the will of God for humanity, founded upon the perfections of God, which directs and binds everyone to personal, complete, exact, and perpetual conformity. The moral law applies to the whole man, body and soul,"
verses = "Deuteronomy 5:1-3, 31-33; Luke 10:26-27; 1 Thessalonians 5:23; Ephesians 4:24"

[[sections]]
text = "and includes the performances of all those duties of holiness and righteousness which he owes to God and man."
verses = "Luke 1:75; Acts 24:16; 1 Peter 1:15-16"

[[sections]]
text = "God promised life for keeping it and threatened death for disobeying it."
verses = "Romans 10:5; Galatians 3:10-12; Romans 5:12"
