id = "87"
question = "Is there any use of the moral law to man since the Fall?"

[[sections]]
text = "Although after the fall no one can attain to righteousness and life by means of the moral law,"
verses = "Romans 8:3; Galatians 2:16"

[[sections]]
text = "it is still of great use and still applies to all men, whether unregenerate or the regenerate."
verses = "1 Timothy 1:8"
