id = "88"
question = "Of what use is the moral law to all men?"

[[sections]]
text = "The moral law is of use to all men because it informs them of the holy nature and will of God"
verses = "Romans 1:20; Leviticus 11:44-45; Leviticus 20:7-8; Romans 7:12"

[[sections]]
text = "and because it informs them of their duty to live by it."
verses = "Micah 6:8; James 2:10-11; Romans 1:32"

[[sections]]
text = "It also reveals to them the sinful pollution of their nature, hearts, and lives, which convinces them that they are unable to keep it."
verses = "Psalm 19:11-12; Romans 3:20; Romans 7:7"

[[sections]]
text = "The moral law also humbles men with the recognition of their sinfulness and misery"
verses = "Romans 3:9-23"

[[sections]]
text = "and thereby gives them a better awareness of their need for Christ and for the perfection of His obedience."
verses = "Galatians 3:21-24; Romans 10:4"
