id = "89"
question = "Of what particular use is the moral law to unregenerate men?"

[[sections]]
text = "The moral law is of particular use to unregenerate men because it awakens their consciences to flee from the coming wrath"
verses = "Psalm 51:13; 1 Timothy 1:9-11"

[[sections]]
text = "and so drive them to Christ."
verses = "Galatians 3:24"

[[sections]]
text = "However, if they continue in their unregenerate and sinful condition, the moral law has left them without excuse"
verses = "Romans 1:20; Romans 2:15"

[[sections]]
text = "and under its curse."
verses = "Galatians 3:10"
