id = "90"
question = "Of what particular use is the moral law to regenerate men?"
[[sections]]
text = "Although those who are regenerate are freed from the moral law as a covenant of works, so that they are neither justified"
verses = "Romans 6:14; Romans 7:4-6; Galatians 4:4-5; Colossians 2:13-14"
[[sections]]
text = "nor condemned"
verses = "Romans 3:20"
[[sections]]
text = "by it, the moral law is of particular use to believers because it shows them how much they owe to Christ for fulfilling it and for enduring its curse in their place and for their good."
verses = "Galatians 5:22-23; Romans 8:1"
[[sections]]
text = "This recognition provokes believers to greater thankfulness,"
verses = "Romans 7:24-25; Galatians 3:13-14; Romans 8:3-4; Acts 13:38-39"
[[sections]]
text = "so that they would take greater care to conform themselves to the moral law as the rule of their obedience."
verses = "Luke 1:68-75; Colossians 1:12-14; Romans 6:14"
[[sections]]
text = ""
verses = "Deuteronomy 30:19-20; Romans 7:22; Romans 12:2; Titus 2:11-14; James 1:25"