id = "91"
question = "Where is the moral law summarized?"
[[sections]]
text = "The moral law is summarized in the Ten Commandments, which were delivered by the voice of God on Mount Sinai and written down by Him on two stone tablets."
verses = "Deuteronomy 4:13; Deuteronomy 10:4; Exodus 34:1-4; Romans 13:8-10; James 2:8-12"
[[sections]]
text = "The first four commandments establish our obligations to God and the remaining six our obligations to human beings."
verses = "Matthew 22:37-40; Matthew 19:17-19"