id = "92"
question = "What is the sum of the Ten Commandments?"
[[sections]]
text = "The sum of the four commandments containing our duty to God is, to love the Lord our God with all our heart, and with all our soul, and with all our strength, and with all our mind."
verses = "Luke 10:27; Matthew 22:37-40"
[[sections]]
text = "The sum of the six commandments which contain our duty to man is, to love our neighbor as ourselves,"
verses = "Matthew 22:39"
[[sections]]
text = "and to do to others what we would have them to do to us."
verses = "Matthew 7:12"