id = "93"
question = "What is the preface to the Ten Commandments?"
[[sections]]
text = "The preface to the Ten Commandments is: I am the LORD your God, who brought you out of the land of Egypt, out of the land of slavery."
verses = "Exodus 20:2"
[[sections]]
text = "In these words God reveals His sovereign being as LORD, in and of Himself,"
verses = "Exodus 3:14"
[[sections]]
text = "eternal, unchangeable, and almighty God,"
verses = "Isaiah 44:6"
[[sections]]
text = "who gives being to all His words"
verses = "Exodus 6:3"
[[sections]]
text = "and works."
verses = "Acts 17:24-28"
[[sections]]
text = "God also points here to His covenantal relationship with the Israelites in ancient times and with all His people,"
verses = "Genesis 17:7; Romans 3:29"
[[sections]]
text = "so that just as He brought the Israelites out of their slavery in Egypt, He delivers us from spiritual enslavement."
verses = "Luke 1:74-75"
[[sections]]
text = "Consequently, we are bound to accept only Him as our God and to keep all His commandments."
verses = "1 Peter 1:15-18; Leviticus 18:30; Leviticus 19:37"
