id = "94"
question = "What are the guidelines for the proper understanding of the Ten Commandments?"
[[sections]]
text = "In order to understand the ten commands properly, these guidelines should be followed: 1. The law is perfect and binds the whole person to observe it completely, and according to its standard, to be completely righteous, and perfectly obey every one of its obligations forever. Moreover, the law forbids even the slightest or partial commission of any sin."
verses = "Psalm 19:7; James 2:10; Matthew 5:21-22"
[[sections]]
text = "2. Since it is spiritual, the law involves our understanding, our will, our emotions, and all the other faculties of the soul, as well as our words, actions, and self-expressions."
verses = "Romans 7:14; Deuteronomy 6:5; Matthew 22:37-39; Matthew 5:21-22, 27-28, 33-34, 37-39, 43-44"
[[sections]]
text = "3. Different aspects of one and the same thing may be required or forbidden in several different commandments."
verses = "Colossians 3:5; Amos 8:5; Proverbs 1:19; 1 Timothy 6:10"
[[sections]]
text = "4. Where a duty is commanded, the opposite is forbidden; and, where a specific sin is forbidden, its opposite is commanded. In the same way, when a requirement of the law adds a promise of blessing for obedience, that promise also includes a warning for disobedience."
verses = "Isaiah 58:13; Deuteronomy 6:13; Matthew 4:9-10; Matthew 15:4-6"
[[sections]]
text = "When a warning is added, an opposite promises is included."
verses = "Matthew 5:21-25; Ephesians 4:28"
[[sections]]
text = "5. What God forbids must never be done at any time or under any circumstances."
verses = "Exodus 20:12; Proverbs 30:17"
[[sections]]
text = "What he commands always remains an obligation,"
verses = "Jeremiah 18:7-8; Exodus 20:7; Psalm 15:1, 4-5; Psalm 24:4-5"
[[sections]]
text = "although every particular obligation of the law does not apply in all circumstances or at all times."
verses = "Job 13:7-8; Romans 3:8; Job 36:21; Hebrews 11:25"
[[sections]]
text = "6. The prohibitions against specific sins and the commandments to observe specific obligations are typical and so cover not just those particular sins or obligations but all others of the same kind. They similarly include all the contributory causes, means, opportunities, and appearances related to these sins and obligations."
verses = "Deuteronomy 4:8-9; Luke 17:10"
[[sections]]
text = "7. Since the provisions of the law apply not only to us but to everyone else, we must try to help others keep those provisions, in the context of our position in life and theirs."
verses = "Matthew 12:7"
[[sections]]
text = "8. Similarly, we must support others in keeping what the law commands them to do or not to do and particularly by not joining them in doing what is forbidden to them."
verses = "Matthew 5:21-22, 27-28; Matthew 15:4-6; 1 Thessalonians 5:22; Jude 23; Galatians 5:26; Colossians 3:21"
[[sections]]
text = ""
verses = "Exodus 20:10; Leviticus 19:17; Genesis 18:19; Joshua 24:15; Deuteronomy 6:6-7; Hebrews 10:24-25"
[[sections]]
text = ""
verses = "2 Corinthians 1:24; 1 Timothy 5:22; Ephesians 5:11"
