id = "96"
question = "What is required in the first commandment?"
[[sections]]
text = "The first commandment requires us to know and recognize God as the only true God and our God"
verses = "1 Chronicles 28:9; Deuteronomy 26:17; Isaiah 43:10; Jeremiah 14:22"
[[sections]]
text = "and to worship and glorify him as such"
verses = "Psalm 95:6-7; Matthew 4:10; Psalm 29:2"
[[sections]]
text = "by valuing, meditating on, remembering,"
verses = "Malachi 3:16; Psalm 63:6; Ecclesiastes 12:1"
[[sections]]
text = "highly regarding, honoring, adoring, preferring, loving, desiring,"
verses = "Psalm 71:19; Psalm 18:1-2; Malachi 1:6; Psalm 45:2-3; Psalm 96; Joshua 24:15-22; Deuteronomy 6:5; Psalm 73:25"
[[sections]]
text = "fearing, believing, trusting, hoping, delighting, and rejoicing in Him."
verses = "Isaiah 8:13; Exodus 14:31; Romans 10:11; Acts 10:43; Isaiah 26:4; Psalm 40:4; Psalm 130:7; Psalm 37:4; Psalm 32:11"
[[sections]]
text = "We must also be zealous for"
verses = "Romans 12:11; Numbers 25:11; Revelation 3:19"
[[sections]]
text = "and call on Him, giving Him all praise and thanks,"
verses = "Philippians 4:6"
[[sections]]
text = "completely obeying and submitting to Him in our whole person."
verses = "Jeremiah 7:23; James 4:7; Romans 12:1"
[[sections]]
text = "Finally, we must walk humbly with Him,"
verses = "Micah 6:8"
[[sections]]
text = "being careful to please Him in everything we say and do,"
verses = "1 John 3:22"
[[sections]]
text = "and being genuinely sorry when we offend Him."
verses = "Jeremiah 31:18-19; Psalm 119:136; Nehemiah 13:8; Psalm 73:21"