id = "97"
question = "What is forbidden in the first commandment?"
[[sections]]
text = "The first commandment forbids: atheism, denying or not believing in God;"
verses = "Psalm 14:1, Ephesians 2:12"
[[sections]]
text = "idolatry, believing in or worshiping any other gods along with or other than the one true God;"
verses = "Jeremiah 2.27-28; 1 Thessalonians 1:9"
[[sections]]
text = "not having and affirming him as God and our God;"
verses = "Psalm 81:11"
[[sections]]
text = "failing or neglecting to do anything this commandment requires relating to God;"
verses = "Isaiah 43:22-24"
[[sections]]
text = "ignorance of him;"
verses = "Jeremiah 4:22, Hosea 4:1-6"
[[sections]]
text = "forgetting him;"
verses = "Jeremiah 2:32, Psalm 50:22"
[[sections]]
text = "misunderstanding him, untrue opinions about him, and evil or unworthy thoughts about him;"
verses = "Acts 17:23-29; Isaiah 40:18; Psalm 50:21"
[[sections]]
text = "irreverent curiosity about and inquiry into His secrets;"
verses = "Deuteronomy 29:29"
[[sections]]
text = "all godless desecration;"
verses = "Titus 1:16; Hebrews 12:16"
[[sections]]
text = "hating God;"
verses = "Romans 1:30; 2 Timothy 3:2"
[[sections]]
text = "self-love and self-interest;"
verses = "Philippians 2:21"
[[sections]]
text = "and all other disorderly or excessive attention, mental, willful, or emotional, to things that divert our attention partially or completely from God."
verses = "1 John 2:15-16; 1 Samuel 2:29; Colossians 3:2-5"
[[sections]]
text = "Also included are: worthless beliefs, lack of faith, heretical beliefs, and wrong beliefs;"
verses = "1 John 4:1; Hebrews 3:12; Galatians 5:20; Titus 3:10; Acts 26:9"
[[sections]]
text = "not trusting God;"
verses = "Psalm 78:22."
[[sections]]
text = "spiritual despair;"
verses = "Genesis 4:13; Ezekiel 37:11"
[[sections]]
text = "refusing correction and resisting God's judgment;"
verses = "Jeremiah 5:3; Isaiah 42:25"
[[sections]]
text = "hardness of heart, pride, willfulness, worldly complacency, and putting God to the test;"
verses = "Romans 2:5; Jeremiah 13:15; Psalm 19:13; Zephaniah 1:12; Matthew 4:7"
[[sections]]
text = "using unlawful means to an end and trusting even in lawful means of grace rather than God;"
verses = "Romans 3:8; Jeremiah 17:5"
[[sections]]
text = "indulging in pleasures of the flesh;"
verses = "2 Timothy 3:4"
[[sections]]
text = "depraved, blind, or improperly directed zeal;"
verses = "Galatians 4:17; John 16:2; Romans 10:2; Luke 9:54-55"
[[sections]]
text = "being lukewarm and spiritual deadness;"
verses = "Revelation 3:16; Revelation 3:1"
[[sections]]
text = "deserting and forsaking God;"
verses = "Ezekiel 14:5; Isaiah 1:4-5"
[[sections]]
text = "praying to or worshiping saints, angels, or any other created being;"
verses = "Romans 10:13-14; Hosea 4:12; Acts 10:25-26; Revelation 19:10; Matthew 4:10; Colossians 2:18; Romans 1:25"
[[sections]]
text = "making an agreement with, consulting, or following the suggestions of the devil;"
verses = "Leviticus 20:6; 1 Samuel 28:7-11; 1 Chronicles 10:13-14; Acts 5:3"
[[sections]]
text = "making men the rulers of our faith and conscience;"
verses = "2 Corinthians 1:24; Matthew 23:9"
[[sections]]
text = "slighting and despising God and his commandments;"
verses = "Deuteronomy 32:15; 2 Samuel 12:9; Proverbs 13:13"
[[sections]]
text = "resisting and grieving his Spirit;"
verses = "Acts 7:51, Ephesians 4:30"
[[sections]]
text = "and finally being dissatisfied and offended by the things God provides in our lives, ignorantly blaming him for the evils he inflicts on us,"
verses = "Psalm 73:2-3, 13-15, 22; Job 1:22"
[[sections]]
text = "as well as attributing the credit for any good thing we are, have, or can do to luck, idols, ourselves, or any other created being."
verses = "1 Samuel 6:7-9; Daniel 5:23; Deuteronomy 8:17; Daniel 4:30; Habakkuk 1:16"
