id = "98"
question = "What are we especially taught by these words before me in the first commandment?"
[[sections]]
text = "The words, before me, in the first commandment teach us that God, who sees everything, takes special note of and is very offended by the sin of having any other god. These words emphasize then how important it is to obey this commandment and how disobeying it insolently provokes God."
verses = "Ezekiel 8:5-18; Psalm 44:20-21"
[[sections]]
text = "They also urge us to be just as mindful of the fact that God sees everything we do as we are doing things in His service."
verses = "1 Chronicles 28:9"