id = "99"
question = "What is the second commandment?"
[[sections]]
text = "The second commandment is: You shall not make for yourself an idol in the form of anything in heaven above or on the earth beneath or in the waters below. You shall not bow down to them or worship them: for I, the LORD your God, am a jealous God, punishing the children for the sin of the fathers to the third and fourth generation of those who hate me, but showing love to a thousand [generations] of those who love me and keep my commandments."
verses = "Exodus 20:4-6"
