id = "100"
question = "What is required in the second commandment?"
[[sections]]
text = "The second commandment requires us to receive, respectfully perform, and preserve completely and purely all the regulations for religion and worship that God has established in His word."
verses = "Deuteronomy 32:46-47; Matthew 28:20; Acts 2:42; 1 Timothy 6:13-14"
[[sections]]
text = "These include: prayer and thanksgiving in the name of Christ;"
verses = "Philippians 4:6; Ephesians 5:20"
[[sections]]
text = "the reading, preaching, and hearing of the word;"
verses = "Deuteronomy 17:18-19; Acts 15:21; 2 Timothy 4:2; James 1:21-22; Acts 10:33"
[[sections]]
text = "the administration of and receiving the sacraments;"
verses = "Matthew 28:19; 1 Corinthians 11:23-30"
[[sections]]
text = "church government and discipline;"
verses = "Matthew 18:15-17; Matthew 16:19; 1 Corinthians 5; 1 Corinthians 12:28; John 20:23"
[[sections]]
text = "the administration and upkeep of the church;"
verses = "Ephesians 4:11-12; 1 Timothy 5:17-18; 1 Corinthians 9:1-15"
[[sections]]
text = "religious fasting;"
verses = "1 Corinthians 7:5; Joel 2:12-18"
[[sections]]
text = "swearing by the name of God;"
verses = "Deuteronomy 6:13"
[[sections]]
text = "and making vows to Him."
verses = "Isaiah 19:21; Psalm 76:11; Psalm 116:14-18"
[[sections]]
text = "Also included are disapproving, denouncing, and opposing false worship"
verses = "Acts 17:16-17; Psalm 16:4"
[[sections]]
text = "and striving, in accordance with our position and calling in life, to eliminate it and all forms of idolatry."
verses = "Deuteronomy 7:5; Isaiah 30:22"
