id = "101"
question = "What is forbidden in the second commandment?"
[[sections]]
text = "The second commandment forbids: imagining,"
verses = "Numbers 15:39"
[[sections]]
text = "recommending,"
verses = "Deuteronomy 13:6-8"
[[sections]]
text = "demanding,"
verses = "Hosea 5:11; Micah 6:16"
[[sections]]
text = "practicing,"
verses = "1 Kings 11:33; 12:33"
[[sections]]
text = "or in any way approving any religious worship not established by God Himself;"
verses = "Deuteronomy 12:30-32"
[[sections]]
text = "creating any likeness of God as the Trinity or as anyone of his three persons, either internally in our minds or externally in the form of any kind of image or representation of a created being;"
verses = "Deuteronomy 4:15-19; Acts 17:29; Romans 1:21-25"
[[sections]]
text = "any worship of such created likenesses"
verses = "Daniel 3:18; Galatians 4:8"
[[sections]]
text = "as if God were in them or as if they were a means to worshiping Him;"
verses = "Exodus 32:5"
[[sections]]
text = "the creation of any likenesses of invented gods,"
verses = "Exodus 32:8"
[[sections]]
text = "any worship of them or service relating to them;"
verses = "1 Kings 18:26-28; Isaiah 65:11"
[[sections]]
text = "and all superstitious contrivances."
verses = "Acts 17:22; Acts 19:19; Colossians 2:21-23"
[[sections]]
text = "Also forbidden are: any departure from the true worship of God"
verses = "Malachi 1:7-14"
[[sections]]
text = "by adding to or taking away from it,"
verses = "Deuteronomy 4:2"
[[sections]]
text = "whether by our own invention"
verses = "Psalm 106:39"
[[sections]]
text = "or received from some other tradition,"
verses = "Matthew 15:9"
[[sections]]
text = "and whether justified by antiquity,"
verses = "1 Peter 1:18"
[[sections]]
text = "custom,"
verses = "Jeremiah 44:17"
[[sections]]
text = "devotional practice,"
verses = "Isaiah 65:3-5; Galatians 1:13-14"
[[sections]]
text = "good intentions, or any other excuse;"
verses = "1 Samuel 13:11-12; 1 Samuel 15:21"
[[sections]]
text = "simony"
verses = "Acts 8:18"
[[sections]]
text = "and anything sacrilegious;"
verses = "Romans 2:22; Malachi 3:8"
[[sections]]
text = "and finally any neglect of,"
verses = "Exodus 4:24-26"
[[sections]]
text = "contempt for,"
verses = "Matthew 22:5; Malachi 1:7-13"
[[sections]]
text = "hindering,"
verses = "Matthew 23:13"
[[sections]]
text = "or opposition to the worship and regulations established by God."
verses = "Acts 13:44-45; 1 Thessalonians 2:15-16"
