id = "102"
question = "What are the reasons annexed to the second commandment?"
[[sections]]
text = "The reason added to this commandment to emphasize its importance is in these words: For I, the LORD your God, am a jealous God, punishing the children for the sin of the fathers to the third and fourth generation of those who hate me, but showing love to a thousand [generations] of those who love me and keep my commandments."
verses = "Exodus 20:5-6"
[[sections]]
text = "In addition to calling attention to the fact that God totally rules over us so that we belong to Him,"
verses = "Psalm 45:11; Revelation 15:3-4"
[[sections]]
text = "these words point to His fervent eagerness to be worshiped correctly,"
verses = "Exodus 34:13-14"
[[sections]]
text = "and that He is angered and takes vengeance on all false worship, which he sees as spiritual prostitution."
verses = "1 Corinthians 10:20-22; Jeremiah 7:18-20; Ezekiel 16:26-27; Deuteronomy 32:16-20"
[[sections]]
text = "He views breaking this commandment as equivalent to hating Him and threatens to punish those who do break it for several generations."
verses = "Hosea 2:2-4"
[[sections]]
text = "He also equates observing this commandment with loving Him and keeping all His commandments, and promises mercy for many generations to those who do it."
verses = "Deuteronomy 5:29"