id = "103"
question = "What is the third commandment?"
[[sections]]
text = "The third commandment is: You shall not misuse the name of the LORD your God, for the LORD will not hold anyone guiltless who misuses His name."
verses = "Exodus 20:7"
