id = "104"
question = "What is required in the third commandment?"
[[sections]]
text = "The third commandment requires the holy and reverent use in our thought, meditations, words, and writing,"
verses = "Malachi 3.16; Psalm 8; Colossians 3.17; Psalm 105:2,5; Psalm 102:18"
[[sections]]
text = "of God's name; titles; qualities;"
verses = "Matthew 6.9; Deuteronomy 28:58; Psalm 29:2; Psalm 68:4; Revelation 15:3-4"
[[sections]]
text = "regulations;"
verses = "Malachi 1:14; Ecclesiastes 5:1"
[[sections]]
text = "word, sacraments and prayer;"
verses = "Psalm 138:2; 1 Corinthians 11:24-25, 28-29; 1 Timothy 2:8"
[[sections]]
text = "oaths and vows;"
verses = "Jeremiah 4:2; Ecclesiastes 5:2-6; Psalm 76:11"
[[sections]]
text = "casting lots,"
verses = "Acts 1:24-26"
[[sections]]
text = "His works,"
verses = "Job 36:24; Psalm 107:21-22"
[[sections]]
text = "and anything else by which He makes Himself known. This treatment will be reflected in holy affirmations of our faith and conduct that matches our affirmations,"
verses = "1 Peter 3:15; Philippians 1:27"
[[sections]]
text = "to the glory of God"
verses = "1 Corinthians 10.31"
[[sections]]
text = "and the good of ourselves and others."
verses = "Jeremiah 32:39; 1 Peter 2:12"
