id = "105"
question = "What is forbidden in the third commandment?"
[[sections]]
text = "The third commandment forbids: not using God's name as is required;"
verses = "Malachi 2:2"
[[sections]]
text = "the abuse of it through ignorance, empty or unholy treatment;"
verses = "Acts 17:23; Proverbs 30:9"
[[sections]]
text = "irreverence;"
verses = "Malachi 1:6-7, 12; Malachi 3:14"
[[sections]]
text = "superstition,"
verses = "1 Samuel 4:3-5; Jeremiah 7:4, 9-10,14,31; Colossians 2:20-22"
[[sections]]
text = "or any wicked reference to his titles, qualities,"
verses = "2 Kings 18:30,35; Exodus 5:2; Psalm 139:20"
[[sections]]
text = "regulations, or works;"
verses = "Psalm 50:16-17; Isaiah 5:12"
[[sections]]
text = "blasphemy;"
verses = "2 Kings 19:22; Leviticus 24:11"
[[sections]]
text = "perjury;"
verses = "Zechariah 5:4; Zechariah 8:17"
[[sections]]
text = "all sinful cursing;"
verses = "1 Samuel 17:43; 2 Samuel 16:5; Romans 12:14"
[[sections]]
text = "oaths and vows;"
verses = "Jeremiah 5:7; Jeremiah 23:10; Deuteronomy 23:18; Acts 23:12-14"
[[sections]]
text = "and casting lots;"
verses = "Esther 3:7; Esther 9:24; Psalm 22:18"
[[sections]]
text = "violating our oaths and vows, if lawful,"
verses = "Psalm 24:4; Ezekiel 17:16-19"
[[sections]]
text = "and keeping them, if aimed at unlawful things;"
verses = "Mark 6:26; 1 Samuel 25:22, 32-34"
[[sections]]
text = "complaining and quarreling about"
verses = "Romans 9:14, 19-20"
[[sections]]
text = "or misapplication of God's decrees and acts of providence."
verses = "Romans 3:5-7; Romans 6:1"
[[sections]]
text = "Also forbidden are: misinterpreting or misapplying God's word or perverting all or part of its meaning in any way;"
verses = "Matthew 5:21-48; Ezekiel 13:22; 2 Peter 3:16; Matthew 22:23-32"
[[sections]]
text = "blasphemous mockery of His word,"
verses = "Isaiah 22:13; Jeremiah 23:34-38; Ephesians 5:4"
[[sections]]
text = "pointless arguing, meaningless talk, or supporting false doctrines;"
verses = "1 Timothy 1:4-7; 1 Timothy 6:4-5, 20; 2 Timothy 2:14; Titus 3:9"
[[sections]]
text = "abusing God's name, His creatures, or anything included under his name in the practice of magic"
verses = "Deuteronomy 18: 10-14; Acts 19:13"
[[sections]]
text = "or to promote sinful desires and activities;"
verses = "2 Timothy 4:3-4; Romans 13:13-14; 1 Kings 21:9-10; Jude 4"
[[sections]]
text = "maligning, scorning, reviling,"
verses = "Acts 13.45; 1 John 3.12; Psalm 1:1; 2 Peter 3:3; 1 Peter 4:4"
[[sections]]
text = "or opposing in any way God's truth, grace, and actions;"
verses = "Acts 13:45-50; Acts 4:18; Acts 19:9; 1 Thessalonians 2:16; Hebrews 10:29"
[[sections]]
text = "pretending to be religious or using religion for evil purposes;"
verses = "2 Timothy 3:5, Matthew 23:14; Matthew 6:1-5, 16"
[[sections]]
text = "being ashamed of God's name"
verses = "Mark 8:38"
[[sections]]
text = "or a shame to it by stubbornly refusing to obey him"
verses = "Psalm 73:14-15"
[[sections]]
text = "and by living unwisely,"
verses = "1 Corinthians 6:5-6; Ephesians 5:15-17"
[[sections]]
text = "unfruitfully,"
verses = "Isaiah 5:4; 2 Peter 1:8-9"
[[sections]]
text = "or in such a way as to offend him or backslide away from him."
verses = "Romans 2:23-24; Galatians 3:1-3; Hebrews 6:6"
