id = "106"
question = "What is the reason annexed to the third commandment?"
[[sections]]
text = "The reasons are in these words: for the LORD will not hold anyone guiltless who misuses His name. Because He is the LORD and our God, His name must never be treated as unholy or misused by us in any way,"
verses = "Leviticus 19:12"
[[sections]]
text = "particularly since He is so opposed to acquitting or sparing those who break this commandment that He will not allow them to escape His righteous punishment,"
verses = "Ezekiel 36:21-23; Deuteronomy 28:58-59; Zechariah 5:2-4"
[[sections]]
text = "even though many who do break this commandment escape human condemnation and punishment."
verses = "1 Samuel 2:12-24; 1 Samuel 3:13"
