id = "107"
question = "What is the fourth commandment?"
[[sections]]
text = "The fourth commandment is: Remember the Sabbath day by keeping it holy. Six days shall you labor and do all your work, but the seventh day is a Sabbath to the LORD your God. On it you shall not do any work, neither you, nor your son or daughter, nor your manservant or maidservant, nor your animals, nor the alien within your gates. For in six days the LORD made the heavens and the earth, the sea, and all that is in them, but he rested on the seventh day. Therefore the LORD blessed the Sabbath day and made it holy."
verses = "Exodus 20:8-11"
