id = "108"
question = "What is required in the fourth commandment?"
[[sections]]
text = "The fourth commandment requires all men to sanctify or set apart to God the times He has established in His Word, and specifically one whole day out of every seven. This was the seventh day from the creation of the world to the resurrection of Christ, and the first day of the week ever since, which will continue until the end of the world. This is the Christian Sabbath,"
verses = "Deuteronomy 5:12-14; Genesis 2:2-3; 1 Corinthians 16:1-2; Acts 20:7; Matthew 5:17-18; Isaiah 56:2-7; Luke 23:56; John 20:19-27"
[[sections]]
text = "in the New Testament called the Lord's day."
verses = "Revelation 1:10"