id = "109"
question = "How is the Sabbath to be sanctified?"
[[sections]]
text = "The Sabbath is to be sanctified by a holy resting for the whole day,"
verses = "Exodus 20:8-10"
[[sections]]
text = "even from such worldly employments and recreations as are lawful on other days."
verses = "Exodus 16:25-29; Nehemiah 13:15-22; Jeremiah 17:21-22"
[[sections]]
text = "Except for necessary works or acts of mercy,"
verses = "Matthew 11:1-13; Matthew 12:1-14"
[[sections]]
text = "we should joyfully spend all our time publicly and privately worshiping God."
verses = "Isaiah 58:13,18; Isaiah 66:23; Luke 4:15-16; Acts 20:7; 1 Corinthians 16:1-2; Leviticus 23:3"
[[sections]]
text = "To that end, we must prepare our hearts and carefully plan ahead so that our worldly business is taken care of beforehand in order that we may more readily spend the day the way God requires."
verses = "Exodus 20:8; Luke 23:54-56; Exodus 16:22-29; Nehemiah 13:19"
