id = "110"
question = "What is forbidden in the fourth commandment?"
[[sections]]
text = "The fourth commandment forbids failing to do anything required by the commandment;"
verses = "Ezekiel 22:26"
[[sections]]
text = "or doing it carelessly, negligently, or in such a way as not to benefit from it, and being tired of keeping it;"
verses = "Acts 20:7-9; Ezekiel 33:30-32; Amos 8:5; Malachi 1:13"
[[sections]]
text = "also treating the day as unholy by loafing, by doing anything in itself sinful,"
verses = "Ezekiel 23:38"
[[sections]]
text = "and by all useless works, words, and thoughts about our worldly affairs and recreations."
verses = "Jeremiah 17:24-27; Isaiah 58:13-14"