id = "111"
question = "What are the reasons annexed to the fourth commandment?"
[[sections]]
text = "The reasons added to the fourth commandment to emphasize its importance are first of all implied by its inherent fairness; God allows us six days out of every seven for own affairs and reserves only one for himself, in these words: Six days shall you labor and do all your work."
verses = "Exodus 20:9"
[[sections]]
text = "God also insists that this day belongs to him, The seventh day is a Sabbath to the LORD your God."
verses = "Exodus 20:10"
[[sections]]
text = "And there is the example of God himself, who in six days made the heavens and the earth, the sea, and all that is in them, but rested on the seventh day. Finally God put a blessing on that day, not just by making it a holy day for serving him but also by establishing that our keeping the Sabbath holy will be a blessing to us as well, Therefore the LORD blessed the Sabbath day and made it holy."
verses = "Exodus 20:11"
