id = "112"
question = "Why does the word Remember begin the fourth commandment?"
[[sections]]
text = "The word Remember begins the fourth commandment"
verses = "Exodus 20:8"
[[sections]]
text = "in one respect, because it is highly beneficial to remember it: the word helps us prepare ourselves to keep the commandment,"
verses = "Exodus 16:23; Luke 23:54-56; Mark 15:42; Nehemiah 13:19"
[[sections]]
text = "and when we do, it helps us to do a better job keeping all the other commandments;"
verses = "Psalm 92:13-14; Ezekiel 20:12, 19-20"
[[sections]]
text = "and the word also reminds us to remain ever thankful for the two great benefits of creation and redemption, which contain the essence of true religion."
verses = "Genesis 2:2-3; Psalm 118:22-24; Acts 4:10-11; Revelation 1:10; Hebrews 4:9"
[[sections]]
text = "In another respect, the word \"remember\" reminds us how easy it is to forget to keep the Sabbath,"
verses = "Ezekiel 22:26; Numbers 15:37-40"
[[sections]]
text = "for several reasons. First, keeping the Sabbath is not obvious to our natural, human understanding,"
verses = "Nehemiah 9:14"
[[sections]]
text = "while it additionally restricts our freedom from doing things that are lawful on other days."
verses = "Exodus 34:21"
[[sections]]
text = "And, coming only every seventh day leaves plenty of time for us to become so engrossed with our own worldly affairs that we forget to prepare for the Sabbath or keep it holy."
verses = "Deuteronomy 5:14-15; Amos 8:5; Numbers 15:37-40"
[[sections]]
text = "Finally, Satan himself with the tools at his disposal is hard at work to blot out the glory and even the memory of the Sabbath and so promote the neglect of religion and irreverence."
verses = "Lamentations 1:7; Jeremiah 17:21-23; Nehemiah 13:15-23"