id = "113"
question = "What is the fifth commandment?"
[[sections]]
text = "The fifth commandment is: Honor your father and your mother so that you may live long in the land the LORD your God is giving you."
verses = "Exodus 20:12"