id = "114"
question = "To whom does father and mother refer in the fifth commandment?"
[[sections]]
text = "Father and mother refer not just to our natural parents"
verses = "Proverbs 23:22, 25; Ephesians 6:1-2"
[[sections]]
text = "but to all superiors in age"
verses = "1 Timothy 5:1-2"
[[sections]]
text = "and gifts;"
verses = "Genesis 4:20-22; Genesis 45:8"
[[sections]]
text = "and specifically to those whom God has ordained to be over us in positions of authority, whether in our family,"
verses = "2 Kings 5:13"
[[sections]]
text = "the church,"
verses = "2 Kings 2:12; 2 Kings 13:14; Galatians 4:19"
[[sections]]
text = "or civil government."
verses = "Isaiah 49:23"
[[sections]]
text = "The terms father and mother remind those in authority that, like natural parents, they are responsible for and should act in a loving and tender way, appropriately reflecting their particular relationship, toward those under them;"
verses = "Ephesians 6:4; 2 Corinthians 12:14; 1 Thessalonians 2:7-11; Numbers 11:11-16"
[[sections]]
text = "and those under them are also encouraged to accept their authority more willingly and cheerfully, as if they were their natural parents."
verses = "1 Corinthians 4:14-16"
