id = "115"
question = "What is the general scope of the fifth commandment?"
[[sections]]
text = "The general scope of the fifth commandment is the performance of those duties which we owe to others, depending upon our particular relationship to them, whether over, under, or equal to them."
verses = "Ephesians 5:21; 1 Peter 2:17; Romans 12:10"