id = "116"
question = "What kind of honor is owed to those over us?"
[[sections]]
text = "Those over us deserve respect in our hearts,"
verses = "Malachi 1:6; Leviticus 19:3"
[[sections]]
text = "our words,"
verses = "Proverbs 31:28; 1 Peter 3:6"
[[sections]]
text = "and our actions."
verses = "Leviticus 19:32; 1 Kings 2:19"
[[sections]]
text = "We must pray and give thanks for them,"
verses = "1 Timothy 2:1-2"
[[sections]]
text = "emulate their virtues and gifts,"
verses = "Hebrews 13:7; Philippians 3:17"
[[sections]]
text = "willingly heed and obey their lawful commands and advice,"
verses = "Ephesians 6:1-7; 1 Peter 2:13-14; Romans 13:1-6; Hebrews 13:17; Proverbs 4:3-4; Proverbs 23:22; Exodus 18:19-24"
[[sections]]
text = "submit to their correction,"
verses = "Hebrews 12:9; 1 Peter 2:18-20"
[[sections]]
text = "be faithful to them,"
verses = "Titus 2:9-10"
[[sections]]
text = "and defend"
verses = "1 Samuel 26:15-16; 2 Samuel 18:3; Esther 6:2"
[[sections]]
text = "and support their persons and authority, as is appropriate to their rank and position."
verses = "Matthew 22:21; Romans 13:6-7; 1 Timothy 5:17-18; Galatians 6:6; Genesis 45:11; Genesis 47:12"
[[sections]]
text = "We must also tolerate their imperfections and infirmities and cover them with our love,"
verses = "1 Peter 2:18; Proverbs 23:22; Genesis 9:23"
[[sections]]
text = "so that we will be an honor to them and to their authority."
verses = "Psalm 127:3-5; Proverbs 31:23"