id = "117"
question = "What are the particular sins against those in authority by those under them?"
[[sections]]
text = "The sins of those under authority against those over them are: any failure to perform what is required by them;"
verses = "Matthew 15:4-6"
[[sections]]
text = "being envious of,"
verses = "Numbers 11:28-29; Psalm 106:16"
[[sections]]
text = "holding in contempt,"
verses = "1 Samuel 8:7; Isaiah 3:5"
[[sections]]
text = "or rebelling"
verses = "2 Samuel 15:1-12"
[[sections]]
text = "against their person or position"
verses = "Exodus 21:15; 1 Samuel 10:27"
[[sections]]
text = "as reflected in their lawful advice,"
verses = "1 Samuel 2:25"
[[sections]]
text = "commands, and correction;"
verses = "Deuteronomy 21:18-21"
[[sections]]
text = "cursing at or making fun of them"
verses = "Proverbs 30:11, 17"
[[sections]]
text = "or any kind of stubborn resistance and disgraceful display that brings shame and dishonor to their person and authority."
verses = "Proverbs 19:26"