id = "118"
question = "What is required of those in authority towards those under them?"
[[sections]]
text = "As is appropriate to the position of power they have received from God and to the particular relationship involved, those in authority should love,"
verses = "Colossians 3:19; Titus 2:4"
[[sections]]
text = "pray for,"
verses = "1 Samuel 12:23; Job 1:5"
[[sections]]
text = "and bless those under them."
verses = "1 Kings 8:55-56; Hebrews 7:7; Genesis 49:28"
[[sections]]
text = "They should teach,"
verses = "Deuteronomy 6:6-7"
[[sections]]
text = "advise, and warn them,"
verses = "Ephesians 6:4"
[[sections]]
text = "approving,"
verses = "1 Peter 3:7"
[[sections]]
text = "praising,"
verses = "1 Peter 2:14; Romans 13:3"
[[sections]]
text = "and rewarding those that do well"
verses = "Esther 6:3"
[[sections]]
text = "while disapproving,"
verses = "Romans 13:3-4"
[[sections]]
text = "blaming, and punishing those who do wrong."
verses = "Proverbs 29:15; 1 Peter 2:14; Romans 13:4"
[[sections]]
text = "They should also protect those under them"
verses = "Job 29:12-16; Isaiah 1:10, 17"
[[sections]]
text = "and provide the things they need for soul and body."
verses = "Ephesians 6:4; 1 Timothy 5:8"
[[sections]]
text = "Those in authority should also be examples of serious, wise, and holy behavior so as to bring glory to God"
verses = "1 Timothy 4:12; Titus 2:2-14"
[[sections]]
text = "and honor to themselves"
verses = "1 Kings 3:28"
[[sections]]
text = "and thereby maintain the authority God has bestowed on them."
verses = "Titus 2:15"
