id = "119"
question = "What are the particular sins of those in authority?"
[[sections]]
text = "In addition to failing to do what is required of them"
verses = "Ezekiel 34:2-4"
[[sections]]
text = "and using their position for their own glory,"
verses = "Philippians 2:21; John 5:44; John 7:18"
[[sections]]
text = "ease, profit, or pleasure,"
verses = "Isaiah 56:10-11; Deuteronomy 17:17"
[[sections]]
text = "the sins of those in authority include: commanding things that are unlawful"
verses = "Daniel 3:4-6; Acts 4:17-18"
[[sections]]
text = "or that cannot be accomplished by those under them;"
verses = "Exodus 5:10-19; Matthew 23:2-4"
[[sections]]
text = "persuading,"
verses = "Matthew 14:8; Mark 6:24"
[[sections]]
text = "encouraging,"
verses = "2 Samuel 13:28; Jeremiah 5:30-31"
[[sections]]
text = "and rewarding those under them for doing evil;"
verses = "1 Samuel 3:13; Jeremiah 6:13-14; Ezekiel 13:9-10"
[[sections]]
text = "dissuading, discouraging, and not rewarding them for doing good;"
verses = "John 7:46-49; John 9:28; Colossians 3:21; Exodus 5:17"
[[sections]]
text = "excessive punishment;"
verses = "1 Peter 2:18-20; Hebrews 12:10; Deuteronomy 25:3"
[[sections]]
text = "carelessly exposing or allowing them to do wrong and to be put in the way of temptation or danger;"
verses = "Genesis 38:11, 26; Acts 18:17; Leviticus 19:29; Isaiah 58:7"
[[sections]]
text = "provoking them to anger;"
verses = "Ephesians 6:4"
[[sections]]
text = "and anything that dishonors themselves or undermines their authority by being unjust, imprudent, too severe, or lax."
verses = "Genesis 9:21; 1 Kings 12:13-16; 1 Samuel 2:29-31"
