id = "120"
question = "What is required of equals?"
[[sections]]
text = "Equals are required to pay attention to the dignity and worth of each other"
verses = "1 Peter 2:17"
[[sections]]
text = "by honoring each other above themselves and by rejoicing in each others' gifts and successes as if their own."
verses = "Romans 12:10, 15-16; Philippians 2:3-4"