id = "121"
question = "What are the particular sins of equals?"
[[sections]]
text = "In addition to failing to do what is required of them,"
verses = "Romans 13:8"
[[sections]]
text = "the sins of equals include undervaluing the worth of each other,"
verses = "2 Timothy 3:3; Proverbs 14:21; Isaiah 65:5"
[[sections]]
text = "envying their gifts,"
verses = "Acts 7:9; Galatians 5:26"
[[sections]]
text = "grieving over their success or prosperity,"
verses = "Numbers 12:2; Esther 6:12-13; 1 John 3:12; Matthew 20:15; Luke 15:28-29"
[[sections]]
text = "and trying to lord it over them."
verses = "3 John 9; Luke 22:24-26; Matthew 20:25-27"
