id = "122"
question = "What reason is added to the fifth commandment emphasizing how important it is to obey it?"
[[sections]]
text = "The reason added to the fifth commandment is in these words: so that you may live long in the land the LORD your God is giving you."
verses = "Exodus 20:12"
[[sections]]
text = "These words expressly promise long life and prosperity to all who keep this commandment, if these glorify God and are for their good."
verses = "Deuteronomy 5:16; 1 Kings 8:25; Ephesians 6:2-3"
