id = "124"
question = "What is required in the sixth commandment?"
[[sections]]
text = "The sixth commandment requires us to make every lawful effort to preserve our own life"
verses = "Ephesians 5:28-29; Matthew 10:23"
[[sections]]
text = "and the lives of others."
verses = "1 Kings 18:4; Psalm 82:4; Deuteronomy 22:8"
[[sections]]
text = "We do this by not thinking about or planning,"
verses = "Jeremiah 26:15-16; Acts 23:12, 16-17, 21, 27; Matthew 5:22"
[[sections]]
text = "by controlling our emotions,"
verses = "Ephesians 4:26-27"
[[sections]]
text = "and by avoiding all opportunities,"
verses = "2 Samuel 2:22; Deuteronomy 22:8; Proverbs 22:24-25; 1 Samuel 25:32-33"
[[sections]]
text = "temptations,"
verses = "Matthew 4:6-7, Proverbs 1:10-11,15-16"
[[sections]]
text = "or actions that would promote or lead to the unjust taking of someone's life."
verses = "1 Samuel 24:12; 1 Samuel 26:9-11; Genesis 37:21-22; 1 Kings 21:9-10,19"
[[sections]]
text = "In the pursuit of that goal, we must defend others from violence,"
verses = "Psalm 82:4; Proverbs 24:11-12; 1 Samuel 14:45"
[[sections]]
text = "patiently endure the afflictions from God's hand,"
verses = "James 5:7-11; Hebrews 12:5,9; Luke 21:19"
[[sections]]
text = "have a quiet mind"
verses = "1 Thessalonians 4:11; 1 Peter 3:3-4; Psalm 37:8,11"
[[sections]]
text = "and a cheerful spirit,"
verses = "Proverbs 17:22; 1 Thessalonians 5:16"
[[sections]]
text = "practice temperance in the way we eat,"
verses = "Proverbs 25:16, 27; Proverbs 23:20"
[[sections]]
text = "drink,"
verses = "1 Timothy 5:23; Proverbs 23:29-30"
[[sections]]
text = "take medications,"
verses = "Isaiah 38:21; Matthew 9:12"
[[sections]]
text = "sleep,"
verses = "Psalm 127:2"
[[sections]]
text = "work,"
verses = "Ecclesiastes 5:12; 2 Thessalonians 3:10,12; Proverbs 16:26"
[[sections]]
text = "and play."
verses = "Ecclesiastes 3:4,11; Mark 6.31; 1 Timothy 4:8"
[[sections]]
text = "We should also harbor charitable thoughts,"
verses = "1 Samuel 19:4-5; 1 Samuel 22:13-14; 1 Corinthians 13:4-5"
[[sections]]
text = "love,"
verses = "Romans 13:10; Proverbs 10:12"
[[sections]]
text = "compassion, meekness, gentleness, and kindness."
verses = "Luke 10:33-34, Zechariah 7:9; Colossians 3:12-13"
[[sections]]
text = "Our speech and behavior should be peaceful, mild, and courteous."
verses = "James 3:17; Romans 12:18; 1 Peter 3:8-11; Proverbs 15:1; 1 Corinthians 4:12-13"
[[sections]]
text = "We should be tolerant of others, be ready to be reconciled, patiently put up with and forgive injuries against us, and return good for evil."
verses = "Matthew 5:24; Ephesians 4:2,32; Romans 12:17-21; Colossians 3:13; James 3:17; 1 Peter 2:20"
[[sections]]
text = "Finally, we should provide aid and comfort to those in distress as well as protect and defend the innocent."
verses = "1 Thessalonians 5:14; Job 31:19-20; Matthew 25:35-36; Proverbs 31:8-9; Isaiah 58:7"
