id = "125"
question = "What is forbidden in the sixth commandment?"
[[sections]]
text = "The sixth commandment forbids: taking our own or anyone else's life, except in the pursuit of public justice,"
verses = "Acts 16:28; Proverbs 1:18; Genesis 9:6"
[[sections]]
text = "lawful war,"
verses = "Numbers 35:31-33; Exodus 21:14"
[[sections]]
text = "or necessary defense."
verses = "Jeremiah 48:10; Deuteronomy 20:1; Hebrews 11:32-34"
[[sections]]
text = "It also includes neglecting or withholding the necessary means for the preservation of life."
verses = "Exodus 22:2-3"
[[sections]]
text = "It also includes sinful anger,"
verses = "Matthew 25:42-43; James 2:15-16; Ecclesiastes 6:1-2"
[[sections]]
text = "hatred,"
verses = "Matthew 5:22"
[[sections]]
text = "envy,"
verses = "1 John 3:15; Leviticus 19:17; Proverbs 10:12"
[[sections]]
text = "or desire for revenge;"
verses = "Proverbs 14:30"
[[sections]]
text = "all excessive emotions"
verses = "Romans 12:19"
[[sections]]
text = "and distracting anxieties;"
verses = "Ephesians 4:31; James 4:1"
[[sections]]
text = "intemperate eating, drinking,"
verses = "Matthew 6:31-34"
[[sections]]
text = "working,"
verses = "Luke 21:34; Romans 13:13"
[[sections]]
text = "or playing;"
verses = "Ecclesiastes 12:12; Ecclesiastes 2:22-23; Exodus 20:9-10"
[[sections]]
text = "speaking in a provocative way,"
verses = "Isaiah 5:12; 1 Peter 4:3-4"
[[sections]]
text = "oppressing,"
verses = "Proverbs 15:1; Proverbs 12:18"
[[sections]]
text = "quarreling with,"
verses = "Ezekiel 18:18; Exodus 1:14; Isaiah 3:15"
[[sections]]
text = "hitting, or wounding others,"
verses = "Galatians 5:15; Proverbs 23:29"
[[sections]]
text = "and anything else conducive to the destruction of anyone's life."
verses = "Numbers 35:16-21"
[[sections]]
text = ""
verses = "Exodus 21:18-36; Proverbs 28:17"