id = "127"
question = "What is required in the seventh commandment?"
[[sections]]
text = "The seventh commandment requires us to be sexually pure in body, mind, inclinations,"
verses = "1 Thessalonians 4:4-5; Job 31:1; 1 Corinthians 7:34"
[[sections]]
text = "words, and actions,"
verses = "Colossians 4:6; Ephesians 4:29; 1 Peter 3:2"
[[sections]]
text = "and to maintain that purity in ourselves and others."
verses = "1 Corinthians 7:2, 35-36; Titus 2:4-5"
[[sections]]
text = "We are to monitor what we look at as well as what we experience with our other senses;"
verses = "Job 31:1; Matthew 5:28"
[[sections]]
text = "and we are to live temperately,"
verses = "Acts 24:24-25; Proverbs 23:31,33; Jeremiah 5:7"
[[sections]]
text = "keeping pure company"
verses = "Proverbs 2:16-20; 1 Corinthians 5:9"
[[sections]]
text = "and dressing modestly."
verses = "1 Timothy 2:9"
[[sections]]
text = "Those who cannot control their sexual desires should marry, loving and living together with their spouses."
verses = "1 Corinthians 7:2, 9; Proverbs 5:18-20; 1 Peter 3:7; 1 Corinthians 7:5"
[[sections]]
text = "We should also work hard at whatever we are called to do,"
verses = "Proverbs 31:11, 27-28; 1 Timothy 5:13-14"
[[sections]]
text = "avoiding all opportunities for indecency, and resisting any temptation to say, think, or do anything indecent or obscene."
verses = "Proverbs 5:8; Genesis 39:8-10"