id = "128"
question = "What is forbidden in the seventh commandment?"
[[sections]]
text = "In addition to failing to do what is required,"
verses = "Proverbs 5:7; Proverbs 4:23, 27"
[[sections]]
text = "the seventh commandment forbids adultery, fornication,"
verses = "Hebrews 13:4; Galatians 5:19; Ephesians 5:5"
[[sections]]
text = "rape, incest,"
verses = "2 Samuel 13:14; 1 Corinthians 5:1, 13; Mark 6:18"
[[sections]]
text = "sodomy, and all unnatural desires."
verses = "Romans 1:24-27; Leviticus 20:15-16"
[[sections]]
text = "It also forbids all impure imaginations, thoughts, purposes, and inclinations."
verses = "Matthew 5:28; Matthew 15:19; Colossians 3:5"
[[sections]]
text = "It also forbids all corrupt and nasty talk or listening to such,"
verses = "Ephesians 5:3-4; Proverbs 7:5, 21-22; Proverbs 19:27"
[[sections]]
text = "lewd looks,"
verses = "Isaiah 3:16; 2 Peter 2:14"
[[sections]]
text = "shameless or frivolous behavior, and immodest dress."
verses = "Proverbs 7:10,13"
[[sections]]
text = "It also forbids prohibiting lawful marriages"
verses = "1 Timothy 4:3"
[[sections]]
text = "and allowing unlawful ones."
verses = "Leviticus 18:1-21; Mark 6:18; Malachi 2:11-12"
[[sections]]
text = "It also forbids the condoning, tolerating, or organizing prostitution and visiting prostitutes."
verses = "1 Kings 15:12; 2 Kings 23:7; Deuteronomy 23:17-18; Leviticus 19:29; Jeremiah 5:7; Proverbs 7:24-27"
[[sections]]
text = "It also forbids restrictive vows of celibacy,"
verses = "Matthew 19:10-12"
[[sections]]
text = "unnecessary delays in marrying,"
verses = "1 Corinthians 7:7-9; Genesis 38:26; 1 Timothy 5:14-15"
[[sections]]
text = "having more than one wife or husband at the same time;"
verses = "Malachi 2:14-15; Matthew 19:5; 1 Corinthians 7:2"
[[sections]]
text = "unjust divorce"
verses = "Malachi 2:16; Matthew 5:32"
[[sections]]
text = "or desertion."
verses = "1 Corinthians 7:12-13"
[[sections]]
text = "It also forbids idleness, gluttony, drunkenness,"
verses = "Ezekiel 16:49; Proverbs 23:30-33; Jeremiah 5:7"
[[sections]]
text = "and keeping impure company."
verses = "Genesis 39:10; Proverbs 5:8; Ephesians 5:11"
[[sections]]
text = "It also forbids obscene or pornographic songs, books, pictures, dancing, or theatrical presentations;"
verses = "Ephesians 5:4; Ezekiel 23:14-16; Isaiah 23:15-17; Mark 6:22; Romans 13:13; 1 Peter 4:3"
[[sections]]
text = "and all other encouragement to or indulgence in impure activities by us or others."
verses = "2 Kings 9:30; Jeremiah 4:30; Ezekiel 23:40; Romans 13:14; 2 Peter 2:17-18"