id = "130"
question = "What is required in the eighth commandment?"
[[sections]]
text = "The eighth commandment requires us to act truthfully, faithfully, and justly in our contractual and business relationships with our fellow human beings so that we give to all what they deserve."
verses = "Psalm 15:2-4; Micah 6:8; Zechariah 7:4, 10; Zechariah 8:16-17; Romans 13:7"
[[sections]]
text = "We are to make restitution for anything we have unlawfully acquired from its rightful owner;"
verses = "Leviticus 6:2-5; Luke 19:8"
[[sections]]
text = "we should give and lend freely, according to our ability and the needs of others;"
verses = "Luke 6:30, 38; Ephesians 4:28; Galatians 6:10; Deuteronomy 15:7-10"
[[sections]]
text = "we must moderate our judgment, will, and inclinations about worldly goods;"
verses = "1 Timothy 6:6-9; Galatians 6:14"
[[sections]]
text = "we must exercise prudence in the acquisition,"
verses = "1 Timothy 5:8"
[[sections]]
text = "maintenance, use, and disposition of the things that we need and are appropriate to sustain us humanly and that match our condition in life;"
verses = "Proverbs 27:23-27; Ecclesiastes 2:24; Ecclesiastes 3:12-13; 1 Timothy 6:17-18; Isaiah 38:1; Matthew 11:8"
[[sections]]
text = "we should find something lawful to do in life"
verses = "1 Corinthians 7:20; Genesis 2:15; Genesis 3:19; Ephesians 4:28; Romans 12:5-8"
[[sections]]
text = "and work hard at it;"
verses = "Ephesians 4:28; Proverbs 10:4; Romans 12:11"
[[sections]]
text = "we should be frugal;"
verses = "John 6:12; Proverbs 21:20; Proverbs 12:27"
[[sections]]
text = "and we should avoid unnecessary lawsuits"
verses = "1 Corinthians 6:1-9"
[[sections]]
text = "and should not become liable by putting up security for others or by similar commitments."
verses = "Proverbs 6:1-6; Proverbs 11:15"
[[sections]]
text = "Finally, we must do our best, by all just and lawful means, to acquire, preserve, and increase our own and others' money and possessions."
verses = "Leviticus 25:35; Deuteronomy 22:1-4; Exodus 23:4-5; Genesis 47:14,20; Philippians 2:4; Matthew 22:39"
