id = "131"
question = "What is forbidden in the eighth commandment?"
[[sections]]
text = "In addition to failing to do what is required,"
verses = "James 2:15-16; 1 John 3:17; Proverbs 23:21"
[[sections]]
text = "the eighth commandment forbids: theft and robbery,"
verses = "Ephesians 4:28; Psalm 62:10"
[[sections]]
text = "kidnapping,"
verses = "1 Timothy 1:10; Exodus 21:16"
[[sections]]
text = "and receiving stolen goods."
verses = "Proverbs 29:24; Psalm 50:18"
[[sections]]
text = "It also forbids fraud and dishonest measures,"
verses = "1 Thessalonians 4:6; Proverbs 11:1; Proverbs 20:10"
[[sections]]
text = "removing boundary markers,"
verses = "Deuteronomy 19:14; Proverbs 23:10"
[[sections]]
text = "injustice or bad faith in our contractual relationships or trust agreements."
verses = "Amos 8:5; Psalm 37:21; Luke 16:10-12"
[[sections]]
text = "It also forbids oppression,"
verses = "Ezekiel 22:29; Leviticus 25:17"
[[sections]]
text = "extortion,"
verses = "Matthew 23:25; Ezekiel 22:12"
[[sections]]
text = "usury,"
verses = "Psalm 15:5"
[[sections]]
text = "bribery,"
verses = "Job 15:34; Isaiah 33:15"
[[sections]]
text = "harassing lawsuits,"
verses = "1 Corinthians 6:6-8; Proverbs 3:29-30"
[[sections]]
text = "and unjust expropriation and dispossession of others' land."
verses = "Isaiah 5:8; Micah 2:2"
[[sections]]
text = "It also forbids hoarding goods to increase their price,"
verses = "Proverbs 11:26"
[[sections]]
text = "illegal work or activities,"
verses = "Acts 19:19-25"
[[sections]]
text = "and all other unjust or sinful ways of taking, withholding, or enriching ourselves from what belongs to others."
verses = "Job 20:19; James 5:4; Proverbs 21:6"
[[sections]]
text = "It also forbids the excessive attachment to or display of our worldly goods."
verses = "1 Timothy 6:5; Colossians 3:2; Proverbs 23:5; Psalm 62:10; 1 John 2:15-16"
[[sections]]
text = "It also forbids allowing ourselves to become distracted from trusting God in the way that we acquire, maintain, and use worldly goods."
verses = "Matthew 6:25-34; Ecclesiastes 5:12"
[[sections]]
text = "It also forbids envying the prosperity of others."
verses = "Psalm 73:3; Psalm 37:1, 7; James 5:9"
[[sections]]
text = "It also forbids laziness,"
verses = "2 Thessalonians 3:11; Proverbs 18:9"
[[sections]]
text = "extravagance, wasteful gambling, and all the other ways that needlessly jeopardize our money and possessions"
verses = "Proverbs 21:17; Proverbs 23:20-21; Proverbs 28:19"
[[sections]]
text = "and defraud ourselves of the use and comfort of the things God has given us."
verses = "Ecclesiastes 4:8; Ecclesiastes 6:2; 1 Timothy 5:8; Deuteronomy 12:7; Deuteronomy 16:14"
