id = "133"
question = "What is required in the ninth commandment?"
[[sections]]
text = "The ninth commandment requires that we maintain and promote truthfulness in our dealings with each other and the good reputation of others as well as ourselves."
verses = "Zechariah 8:16; Ephesians 4:25; 3 John 12"
[[sections]]
text = "We must come forward and stand up for the truth,"
verses = "Proverbs 31:8-9"
[[sections]]
text = "speaking the truth and nothing but the truth from our hearts,"
verses = "Psalm 15:2"
[[sections]]
text = "sincerely, freely, clearly, and without equivocation,"
verses = "2 Chronicles 19:9; 1 Samuel 19:4-5; Jeremiah 9:3; Joshua 7:19; Jeremiah 42:4; Acts 20:20, 27; 2 Samuel 14:18-20"
[[sections]]
text = "not only in all matters relating to the law and justice"
verses = "Leviticus 19:15; Proverbs 14:5, 15"
[[sections]]
text = "but in any and every circumstance whatsoever."
verses = "2 Corinthians 1:17-18; Ephesians 4:25; Isaiah 63:8; Colossians 3:9"
[[sections]]
text = "We must have a charitable regard for others,"
verses = "Hebrews 6:9; 1 Corinthians 13:4-7"
[[sections]]
text = "loving, desiring, and rejoicing in their good reputation"
verses = "Romans 1:8; 2 John 4; 3 John 3-4"
[[sections]]
text = "as well as regretting"
verses = "2 Corinthians 2:4; 2 Corinthians 12:21; Psalm 119:158"
[[sections]]
text = "and putting the best light on their failings."
verses = "Proverbs 17:9; 1 Peter 4:8"
[[sections]]
text = "We must freely acknowledge their talents and gifts,"
verses = "1 Corinthians 1:4-7; 2 Timothy 1:4-5"
[[sections]]
text = "defending their innocence,"
verses = "1 Samuel 22:14; Psalm 82:3"
[[sections]]
text = "readily receiving a good report about them and reluctantly admitting a bad one."
verses = "1 Corinthians 13:4-7; Psalm 15:3"
[[sections]]
text = "We should discourage gossips, flatterers, and slanderers;"
verses = "Proverbs 25:23; Proverbs 26:24-25; Psalm 101:5"
[[sections]]
text = "we should love and protect our own good reputation and defend it when necessary;"
verses = "Proverbs 22:1; John 8:49; 2 Corinthians 11:18-23"
[[sections]]
text = "we should keep every lawful promise we make no matter what;"
verses = "Psalm 15:4"
[[sections]]
text = "and finally we should do the best we can to focus our lives and thoughts on things that are true, noble, lovely, and admirable."
verses = "Philippians 4:8"
