id = "134"
question = "What is forbidden in the ninth commandment?"
[[sections]]
text = "The ninth commandment forbids everything detrimental to the truth and the good reputation of others as well as our own,"
verses = "1 Samuel 17:28; 2 Samuel 16:3; 2 Samuel 1:9-16; Luke 3:14"
[[sections]]
text = "with special reference to legal matters in the courts."
verses = "Leviticus 19:15; Habakkuk 1:4"
[[sections]]
text = "We must not give untrue evidence,"
verses = "Proverbs 19:5; Proverbs 6:16, 19"
[[sections]]
text = "commit perjury,"
verses = "Acts 6:13"
[[sections]]
text = "knowingly appear and plead on behalf of an evil cause, or engage in overbearing and boastful exaggeration."
verses = "Jeremiah 9:3-5; Acts 24:2-5; Psalm 12:3-4; Psalm 52:1-4"
[[sections]]
text = "We should never participate in passing an unjust sentence,"
verses = "Proverbs 17:15; 1 Kings 21:9-14"
[[sections]]
text = "call evil good or good evil, or reward the wicked in a way appropriate to the righteous or the righteous in a way appropriate to the wicked."
verses = "Isaiah 5:23"
[[sections]]
text = "Forgery is forbidden,"
verses = "Psalm 119:69; Luke 19:8; Luke 16:5-7; 1 Kings 21:8"
[[sections]]
text = "as is concealing the truth, remaining silent in a just cause,"
verses = "Leviticus 5:1; Deuteronomy 13:8; Acts 5:3-9; 2 Timothy 4:6"
[[sections]]
text = "and not taking it on ourselves to reprove"
verses = "1 Kings 1:6; Leviticus 19:17; Isaiah 58:1"
[[sections]]
text = "or complain to others about some wrong."
verses = "Isaiah 59:4"
[[sections]]
text = "We must not speak the truth at an inappropriate time,"
verses = "Proverbs 29:11"
[[sections]]
text = "or maliciously to promote a wrong purpose,"
verses = "1 Samuel 22:9-10; Psalm 52:1-5"
[[sections]]
text = "nor pervert it into a wrong meaning,"
verses = "Psalm 56:5; John 2:19; Matthew 26:60-61"
[[sections]]
text = "into ambiguous equivocations, or in such ways as to undermine truth and justice."
verses = "Genesis 3:5; Genesis 26:7-9"
[[sections]]
text = "Also forbidden are: saying anything untrue;"
verses = "Isaiah 59:13"
[[sections]]
text = "lying, slandering, backbiting;"
verses = "Leviticus 19:11; Colossians 3:9; Psalm 50:20; Psalm 15:3; Romans 1:30"
[[sections]]
text = "belittling, gossiping, whispering, ridiculing, reviling;"
verses = "James 4:11; Jeremiah 38:4; Titus 3:2; Leviticus 19:16; Romans 1:29-30; Proverbs 16:28; Genesis 21:9; Galatians 4:29; Isaiah 28:22; 1 Corinthians 6:10"
[[sections]]
text = "expressing any kind of judgmental opinion that is rash, harsh, or prejudiced;"
verses = "Matthew 7:1; Acts 28:4; James 2:13; Genesis 38:24; Romans 2:1; John 7:24"
[[sections]]
text = "misconstruing intentions, words, and actions;"
verses = "Nehemiah 6:6-8; Romans 3:8; Psalm 69:10; 1 Samuel 1:13-15; 2 Samuel 10:3"
[[sections]]
text = "flattery and ostentatious boasting;"
verses = "2 Timothy 3:2; Luke 18:11; Proverbs 25:27; Proverbs 27:2; 1 Corinthians 13:4; Psalm 101:5; Exodus 4:10-14"
[[sections]]
text = "thinking or speaking too highly or too poorly of ourselves or others;"
verses = "Luke 18:9-11; Romans 12:16; 1 Corinthians 4:6; Acts 12:22; Exodus 4:10-14"
[[sections]]
text = "denying the gifts of God or the effects of his grace on us;"
verses = "Job 4:6, 27:5-6; Job 32:2; 2 Corinthians 10:10, 12:6"
[[sections]]
text = "exaggerating the significance of trivial faults;"
verses = "Matthew 7:3-5; Isaiah 29:20-21"
[[sections]]
text = "concealing, excusing, or rationalizing our sinful behavior when we are called to confess it voluntarily;"
verses = "Proverbs 28:13; Proverbs 30:20; Genesis 3:12-13; Genesis 4:9; Jeremiah 2:35; 2 Kings 5:25"
[[sections]]
text = "gratuitously revealing the problems and failings of others;"
verses = "Genesis 9:22; Proverbs 25:9-10"
[[sections]]
text = "spreading false rumors, receiving and approving evil reports, and refusing to listen to a just defense;"
verses = "Exodus 23:1; Proverbs 29:12; Jeremiah 20:10; Acts 7:56-57; Job 31:13-14"
[[sections]]
text = "harboring evil suspicions;"
verses = "1 Corinthians 13:4-5; 1 Timothy 6:4"
[[sections]]
text = "being envious of or grieved by the deserved honors others receive, trying to discredit those honors, and rejoicing at someone else's disgrace or evil reputation;"
verses = "Numbers 11:29; Matthew 21:15; Ezra 4:12-13; Daniel 6:3-4; Jeremiah 48:27"
[[sections]]
text = "scornful contempt and foolish admiration;"
verses = "Psalm 35:15-16,21; Matthew 27:28-29; Jude 16; Acts 12:22; 1 Corinthians 4:8"
[[sections]]
text = "breaking our lawful promises;"
verses = "Romans 1:31; 2 Timothy 3:3"
[[sections]]
text = "and, finally, failing to promote everyone's good name,"
verses = "1 Samuel 2:24; 2 Samuel 12:14; Proverbs 6:33"
[[sections]]
text = "and doing, not avoiding, or not hindering in others, as we can, those things that give people a bad name."
verses = "Proverbs 16:21; Isaiah 29:20-21; Genesis 34:30; 2 Samuel 12:14; Proverbs 6:33"
