id = "135"
question = "What is the tenth commandment?"
[[sections]]
text = "The tenth commandment is: You shall not covet your neighbor's house. You shall not covet your neighbor's wife, or his manservant or maidservant, his ox or donkey or anything that belongs to your neighbor."
verses = "Exodus 20:17"
