id = "136"
question = "What is required in the tenth commandment?"
[[sections]]
text = "The tenth commandment requires that we be so completely satisfied with our own status in life,"
verses = "Hebrews 13:5; 1 Timothy 6:6"
[[sections]]
text = "and have such a proper, loving attitude toward others that we are naturally inclined to wish the best for them and all their possessions."
verses = "Job 31:29; Romans 12:15; Psalm 122:7-9; 1 Timothy 1:5; Esther 10:3; 1 Corinthians 13:4-7; Philippians 2:4"
