id = "137"
question = "What is forbidden in the tenth commandment?"
[[sections]]
text = "The tenth commandment forbids any dissatisfaction with what belongs to us,"
verses = "1 Kings 21:4; Esther 5:13; 1 Corinthians 10:10"
[[sections]]
text = "envy"
verses = "Galatians 5:26; James 3:14-16"
[[sections]]
text = "and grief at the success of others,"
verses = "Psalm 112:9-10; Nehemiah 2:10"
[[sections]]
text = "and all improper desire for anything that belongs to someone else."
verses = "Romans 7:7-8; Romans 13:9; Colossians 3:5; Deuteronomy 5:21"
