id = "138"
question = "Can anyone perfectly keep the commandments of God?"
[[sections]]
text = "No mere man, since the Fall, can perfectly keep the commandments of God, either on His own"
verses = "James 3:2; John 15:5; Romans 8:3"
[[sections]]
text = "or from any divine gift received in this life,"
verses = "Ecclesiastes 7:20; 1 John 1:8-2:6; Galatians 5:17; Romans 7:18-19; Psalm 17:15; 1 Kings 8:46"
[[sections]]
text = "but breaks them every day in thought,"
verses = "Genesis 6:5; Genesis 8:21; James 1:14"
[[sections]]
text = "word, and action."
verses = "Romans 3:9-19; James 3:2-13; Psalm 19:12"
