id = "139"
question = "Are all transgressions of the law equally heinous?"
[[sections]]
text = "All transgressions of the law are not equally heinous, but some sins in themselves and others by reason of the harm that results from them are more heinous in the sight of God than others."
verses = "John 19:11; Ezekiel 8:6-15; 1 John 5:16; Psalm 78:17, 32, 56; Ezra 9:14; Hebrews 2:2-3"
