id = "140"
question = "What sins are more heinous because of the harm that results from them?"
[[sections]]
text = "Sins become more harmful: 1. From those who commit the sins:"
verses = "Jeremiah 2:8"
[[sections]]
text = "if they are older,"
verses = "Job 32:7-9; Ecclesiastes 4:13"
[[sections]]
text = "have a longer experience of God's grace,"
verses = "1 Kings 11:4-9"
[[sections]]
text = "are well-known for their faith,"
verses = "2 Samuel 12:14; 1 Corinthians 5:1"
[[sections]]
text = "clearly know better,"
verses = "James 4:17; Luke 12:47-48"
[[sections]]
text = "hold a prominent position or office,"
verses = "Jeremiah 5:4-5; John 3:10; 2 Samuel 12:7-9; Ezekiel 8:11-12"
[[sections]]
text = "are teachers,"
verses = "Romans 2:17-24"
[[sections]]
text = "and whose example will influence others."
verses = "Galatians 2:11-14; 2 Peter 2:2"
[[sections]]
text = "2. From those sinned against:"
verses = "Matthew 21:38-39; 1 John 5:10"
[[sections]]
text = "if directly against God,"
verses = "1 Samuel 2:25; Acts 5:4; Psalm 51:4"
[[sections]]
text = "His attributes,"
verses = "Romans 2:4"
[[sections]]
text = "and worship;"
verses = "Malachi 1:8,14; 1 Corinthians 10:21-22"
[[sections]]
text = "against Christ and His grace;"
verses = "Hebrews 2:2-3; Hebrews 12:25; John 3:18, 36"
[[sections]]
text = "against the Holy Spirit;"
verses = "Hebrews 10:29; Matthew 12:31-32"
[[sections]]
text = "His witness"
verses = "Ephesians 4:30"
[[sections]]
text = "and work;"
verses = "Hebrews 6:4-6"
[[sections]]
text = "against those above us,"
verses = "Jude 8; Numbers 12:8-9; Isaiah 3:5"
[[sections]]
text = "and especially those to whom we are related or owe allegiance;"
verses = "Proverbs 30:17; 2 Corinthians 12:15; Psalm 41:9; Psalm 55:12-15"
[[sections]]
text = "and against any fellow believer,"
verses = "Zephaniah 2:8-11; Matthew 18:6; 1 Corinthians 6:8; Revelation 17:6"
[[sections]]
text = "particularly those who are weaker in the faith,"
verses = "1 Corinthians 8:11-12; Romans 14:13,15,21"
[[sections]]
text = "their souls or anyone else's,"
verses = "Ezekiel 13:19; 1 Corinthians 8:12; Revelation 18:12-13; Matthew 23:15"
[[sections]]
text = "and the general good of everyone."
verses = "1 Thessalonians 2:15-16; Joshua 22:20; Matthew 23:34-38"
[[sections]]
text = "3. From the nature and quality of the sin:"
verses = "Proverbs 6:30-35; Isaiah 3:9"
[[sections]]
text = "if it is against the exact letter of the law,"
verses = "Ezra 9:10-12; 1 Kings 11:9-10; Ezekiel 20:12-13"
[[sections]]
text = "breaks more than one commandment or includes many separate sins;"
verses = "Colossians 3:5; 1 Timothy 6:10; Proverbs 5:8-12; Proverbs 6:32-33; Joshua 7:21"
[[sections]]
text = "if it is not only planned in the heart, but is expressed in words and actions,"
verses = "James 1:14-15; Matthew 5:22; Micah 2:1-2"
[[sections]]
text = "scandalizes others,"
verses = "Matthew 18:7; Romans 2:23-24"
[[sections]]
text = "and cannot be made right;"
verses = "Deuteronomy 22:22, 28-29; Proverbs 6:32-35; Matthew 16:26"
[[sections]]
text = "if it is against the means of God's grace,"
verses = "Matthew 11:21-24; John 15:22"
[[sections]]
text = "His mercy,"
verses = "Isaiah 1:2-3; Deuteronomy 32:6; Ezra 9:13-14"
[[sections]]
text = "or His judgments,"
verses = "Amos 4:8-11; Jeremiah 5:3"
[[sections]]
text = "against our natural understanding,"
verses = "Romans 1:20"
[[sections]]
text = "convictions of conscience,"
verses = "Romans 1:32; Daniel 5:22; Titus 3:10-11"
[[sections]]
text = "public or private warnings,"
verses = "Proverbs 29:1"
[[sections]]
text = "condemnation by the church,"
verses = "Titus 3:10; Matthew 18:17"
[[sections]]
text = "and civil punishment;"
verses = "Proverbs 27:22; Proverbs 23:35; Romans 13:1-5"
[[sections]]
text = "and if it is against our own prayers, purposes, promises,"
verses = "Psalm 78:34-37; Jeremiah 2:20; Jeremiah 42:5-6, 20-22"
[[sections]]
text = "vows,"
verses = "Ecclesiastes 5:4-6; Proverbs 20:25"
[[sections]]
text = "covenants,"
verses = "Leviticus 26:25; Jeremiah 31:32"
[[sections]]
text = "and commitments to God and men"
verses = "Proverbs 2:17; Ezekiel 17:18-19"
[[sections]]
text = "– if made deliberately,"
verses = "Psalm 36:4; Jeremiah 6:16"
[[sections]]
text = "presumptuously,"
verses = "Numbers 15:30; Exodus 21:14; Jeremiah 6:15"
[[sections]]
text = "boastfully,"
verses = "Psalm 52:1; Jeremiah 3:3; Proverbs 7:13"
[[sections]]
text = "maliciously,"
verses = "3 John 10; Ezekiel 35:5-6"
[[sections]]
text = "repeatedly,"
verses = "Numbers 14:22"
[[sections]]
text = "obstinately,"
verses = "Zechariah 7:11-12"
[[sections]]
text = "with delight,"
verses = "Proverbs 2:14"
[[sections]]
text = "continually,"
verses = "Isaiah 57:17; Jeremiah 9:3-5"
[[sections]]
text = "or as a result of falling back into it after repenting from it."
verses = "Jeremiah 34:8-11; 2 Peter 2:20-22; Hebrews 6:4-6"
[[sections]]
text = "4. From circumstances of time and place:"
verses = "2 Kings 5:26; Isaiah 22:12-14; Jeremiah 7:10-11; Isaiah 26:10"
[[sections]]
text = "if on the Lord's day"
verses = "Ezekiel 23:37-39"
[[sections]]
text = "or other times of divine worship,"
verses = "Isaiah 58:3-5; Numbers 25:6-7"
[[sections]]
text = "or immediately before"
verses = "1 Corinthians 11:20-21"
[[sections]]
text = "or after these"
verses = "Jeremiah 7:8-10; Proverbs 7:14-15; John 13:27-30"
[[sections]]
text = "or other religious activities that help to prevent or be a remedy for such failures;"
verses = "Ezra 9:13-14; Nehemiah 9:13-16; 2 Chronicles 36:15-16"
[[sections]]
text = "and if publicly or in the presence of others, who consequently may very well by aroused to or defiled by the sin."
verses = "2 Samuel 16:22; 1 Samuel 2:22-24; Isaiah 3:9"