id = "141"
question = "What does every sin deserve from God?"
[[sections]]
text = "Since even the least sin goes against the sovereignty,"
verses = "James 2:10-11; Malachi 1:14"
[[sections]]
text = "goodness,"
verses = "Exodus 20:1-2; Deuteronomy 32:6"
[[sections]]
text = "and holiness of God,"
verses = "Habakkuk 1:13; Leviticus 10:3; Leviticus 11:44-45; 1 Peter 1:15-16"
[[sections]]
text = "and against His righteous law,"
verses = "1 John 3:4; Romans 7:12"
[[sections]]
text = "every sin deserves God's wrath and curse,"
verses = "Ephesians 5:6; Galatians 3:10"
[[sections]]
text = "both in this life"
verses = "Lamentations 3:39; Deuteronomy 28:15-29; Proverbs 13:21"
[[sections]]
text = "and the life to come,"
verses = "Matthew 25:41; Romans 6:21-23"
[[sections]]
text = "and cannot be expiated except by the blood of Christ."
verses = "Hebrews 9:22; 1 Peter 1:18-19; 1 John 1:7"