id = "142"
question = "What does God require of us, that we may escape His wrath and curse, due to us for sin?"
[[sections]]
text = "To escape the wrath and curse of God due to us for sin, God requires from us faith in Jesus Christ and repentance unto life,"
verses = "Acts 20:21; Acts 16:30-31; Matthew 3:7-8; Luke 13:3-5; John 3:16-18; Mark 1:15"
[[sections]]
text = "along with the diligent use of all the outward and ordinary means whereby Christ communicates to us the benefits of His mediation."
verses = "Proverbs 2:1-5; Proverbs 8:33-36; Matthew 28:19-20; Acts 2:42-46; 1 Timothy 4:16; 1 Corinthians 1:21; Ephesians 5:19-20; Ephesians 6:17-18"