id = "143"
question = "What are the outward and ordinary means whereby Christ communicates to us the benefits of redemption?"
[[sections]]
text = "The outward and ordinary means whereby Christ communicates to us the benefits of redemption are His ordinances, particularly the Word, sacraments, and prayer; all of which are made effectual to the elect for salvation."
verses = "Matthew 28:19-20; Acts 2:42-47; 1 Timothy 4:16; 1 Corinthians 1:21; Ephesians 5:19-20; Ephesians 6:17-18"
