id = "144"
question = "How is the Word made effectual to salvation?"
[[sections]]
text = "The Spirit of God causes the reading and especially the preaching of the Word to enlighten,"
verses = "Nehemiah 8:8; Acts 26:18; Acts 17:11-12; Psalm 19:8"
[[sections]]
text = "convince, and humble sinners."
verses = "1 Corinthians 14:24-25; 2 Chronicles 34:18-19, 26-28; Jeremiah 23:28-29; Hebrews 4:12"
[[sections]]
text = "The Spirit drives sinners out of themselves and draws them to Christ;"
verses = "Acts 2:37-41; Acts 8:27-39"
[[sections]]
text = "He conforms them to His image"
verses = "2 Corinthians 3:18; Colossians 1:27"
[[sections]]
text = "and subdues them to His will;"
verses = "2 Corinthians 10:4-6; Romans 6:17"
[[sections]]
text = "He strengthens them against temptations and corrupting influences;"
verses = "Matthew 4:4,7,10; Ephesians 6:16-17; Psalm 19:11; 1 Corinthians 10:11; Colossians 1:28"
[[sections]]
text = "and He builds them up in God's grace"
verses = "Acts 20:32; 2 Timothy 3:15-16; Ephesians 4:11-12; 1 Corinthians 3:9-11"
[[sections]]
text = "and establishes their hearts in holiness and comfort through faith to salvation."
verses = "Romans 16:25; 1 Thessalonians 3:2, 10-13; Romans 15:4; Romans 10:13-17; Romans 1:16"
