id = "145"
question = "How should the Word of God be read?"
[[sections]]
text = "We must read the Word of God with high and reverent esteem,"
verses = "Psalm 19:10; Psalm 119:97; Nehemiah 8:3-6; Exodus 24:7; 2 Chronicles 34:27; Isaiah 66:2"
[[sections]]
text = "being absolutely convinced that it is truly God's Word"
verses = "2 Peter 1:16-21; 1 Thessalonians 2:13"
[[sections]]
text = "and that only He can enable us to understand it."
verses = "Luke 24:44-48; 2 Corinthians 3:13-16; Psalm 119:18"
[[sections]]
text = "We should read with a desire to know, believe, and obey His will as revealed in the Bible."
verses = "Deuteronomy 17:10, 20; James 1:21-22; 1 Peter 2:2; Mark 4:20"
[[sections]]
text = "We should pay careful attention"
verses = "Acts 17:11; Deuteronomy 11:13"
[[sections]]
text = "to its content and the extent of its meaning,"
verses = "Acts 8:30-34; Luke 10:26-28; Matthew 13:23"
[[sections]]
text = "meditate on it,"
verses = "Psalm 1:2; Psalm 119:97"
[[sections]]
text = "apply it to our lives,"
verses = "2 Chronicles 34:21; Acts 2:38-39; 2 Samuel 12:7"
[[sections]]
text = "deny ourselves under its direction,"
verses = "Proverbs 3:5; Deuteronomy 33:3; Galatians 1:15"
[[sections]]
text = "and use it as a basis for our prayers."
verses = "Proverbs 2:1-6; Psalm 119:18; Luke 24:45"