id = "146"
question = "Who should preach the Word of God?"
[[sections]]
text = "The Word of God should be preached only by those who are sufficiently gifted"
verses = "1 Timothy 3:2-7; Titus 1:7-9; Timothy 2:1-2; Malachi 2:6-7; 2 Corinthians 3:5-6"
[[sections]]
text = "and who are properly approved and called to do it."
verses = "Jeremiah 14:14-15; Romans 10:14-15; Hebrews 5:1-4; 1 Timothy 4:14-16; 1 Timothy 5:22"
