id = "147"
question = "How should those who are called preach the Word of God?"
[[sections]]
text = "Those who are called to labor in the ministry of the word should preach sound doctrine,"
verses = "Titus 2:1,7-8"
[[sections]]
text = "accurately,"
verses = "Acts 18:24-28; 2 Timothy 2:15"
[[sections]]
text = "in season and out of season,"
verses = "2 Timothy 4:2"
[[sections]]
text = "clearly,"
verses = "1 Corinthians 14:19"
[[sections]]
text = "and not with seductive words of human wisdom but with a demonstration of the Spirit and of power."
verses = "1 Corinthians 2:4"
[[sections]]
text = "They should faithfully"
verses = "Jeremiah 23:28-29; 1 Corinthians 4:1-2; Matthew 24:45-47"
[[sections]]
text = "and fully express the whole counsel of God."
verses = "Acts 20:27"
[[sections]]
text = "This should be done wisely,"
verses = "Colossians 1:27-28"
[[sections]]
text = "taking into account the needs and capabilities of the audience."
verses = "1 Corinthians 3:2; Hebrews 5:12-14; 1 Thessalonians 2:7"
[[sections]]
text = "Their preaching should be motivated by a zealous"
verses = "Acts 18:24-28; 2 Timothy 4:5"
[[sections]]
text = "and fervent love for God"
verses = "2 Corinthians 5:13-14; Philippians 1:15-17"
[[sections]]
text = "and the souls of his people."
verses = "Colossians 4:12; 2 Corinthians 12:15; 2 Corinthians 5:13; Philippians 1:15-17; 1 Thessalonians 3:12"
[[sections]]
text = "Finally, it should be done sincerely,"
verses = "2 Corinthians 2:17; 2 Corinthians 4:2"
[[sections]]
text = "aiming to glorify God"
verses = "1 Thessalonians 2:3-6; John 7:18"
[[sections]]
text = "and to convert,"
verses = "1 Corinthians 9:19-22"
[[sections]]
text = "edify,"
verses = "2 Corinthians 12:19; Ephesians 4:12"
[[sections]]
text = "and save"
verses = "1 Timothy 4:16; 2 Timothy 2:10; Acts 26:16-18"
[[sections]]
text = "his people."
verses = ""
