id = "148"
question = "What is required of those who hear the word preached?"
[[sections]]
text = "Those who hear the word preached must pay careful attention to it,"
verses = "Proverbs 8:32-34; Psalm 84:1-4; Psalm 27:4"
[[sections]]
text = "prepare themselves"
verses = "1 Peter 2:1-2; Luke 8:18; James 1:21"
[[sections]]
text = "and pray for understanding."
verses = "Psalm 119:18; Ephesians 6:18-19"
[[sections]]
text = "They should review carefully what they hear through the Bible"
verses = "Acts 17:11"
[[sections]]
text = "and accept the truths in it faithfully,"
verses = "Hebrews 4:2"
[[sections]]
text = "lovingly,"
verses = "2 Thessalonians 2:9-10"
[[sections]]
text = "humbly,"
verses = "James 1:21; Psalm 25:9"
[[sections]]
text = "and with a ready mind,"
verses = "Acts 17:11; Acts 2:41"
[[sections]]
text = "treating it as it is, the word of God."
verses = "1 Thessalonians 2:13"
[[sections]]
text = "They should meditate on it,"
verses = "Hebrews 2:1"
[[sections]]
text = "talk about it,"
verses = "Deuteronomy 6:6-7; Luke 24:13-33"
[[sections]]
text = "hide it in their hearts,"
verses = "Proverbs 2:1-5; Psalm 119:11"
[[sections]]
text = "and bring forth the fruit of it in their lives."
verses = "Luke 8:15; James 1:25"