id = "149"
question = "What is a sacrament?"
[[sections]]
text = "A sacrament is a holy ordinance established by Christ in His church"
verses = "Genesis 17:7, 10; Exodus 12; Matthew 28:19; Matthew 26:26-28"
[[sections]]
text = "as a sign, seal, and outward display"
verses = "Romans 4:11; 1 Corinthians 11:24-25"
[[sections]]
text = "to those within the covenant of grace"
verses = "Romans 9:8; Romans 15:8; Exodus 12:48; Galatians 3:27-29; Galatians 5:6; Galatians 6:15"
[[sections]]
text = "of the benefits they have from Christ's mediation."
verses = "Acts 2:38; Acts 22:16; 1 Corinthians 10:16"
[[sections]]
text = "It serves to strengthen and increase their faith and other graces in them."
verses = "Romans 4:11; Galatians 3:27; 1 Corinthians 11:24-26"
[[sections]]
text = "It obliges them to obey God"
verses = "Romans 6:3-4; 1 Corinthians 10:21"
[[sections]]
text = "and to witness to and cherish their love and fellowship with each other."
verses = "Ephesians 4:2-5; 1 Corinthians 10:17; 1 Corinthians 12:13"
[[sections]]
text = "Moreover, it distinguishes them from those outside the covenant."
verses = "Ephesians 2:11-12; Genesis 34:14; 1 Corinthians 10:21"
