id = "150"
question = "How do the sacraments become effectual means of salvation?"
[[sections]]
text = "The sacraments become effectual means of salvation, not by any power in them or by any inherent potency coming from the devoutness or the intention of whoever administers them, but rather by the working of the Holy Spirit and the blessing of Christ, who established them."
verses = "1 Peter 3:21; Acts 8:13, 23; 1 Corinthians 3:6-7; 1 Corinthians 6:11; 1 Corinthians 12:13"
