id = "150"
question = "How do the sacraments become effectual means of salvation?"
[[sections]]
text = "The sacraments become effectual means of salvation, not by any power in themselves, nor by any inherent potency coming from the devoutness or intention of whoever administers them,"
verses = "1 Corinthians 3:6-7"
[[sections]]
text = "but solely by the blessing of Christ who established them,"
verses = "Matthew 28:19; 1 Peter 3:21"
[[sections]]
text = "the working of the Holy Spirit,"
verses = "1 Corinthians 12:3, 13; Titus 3:5"
[[sections]]
text = "and through the faith exercised by those who rightly receive them."
verses = "1 Corinthians 11:28; Galatians 3:26-27; Colossians 2:11-12"
