id = "151"
question = "How many sacraments has Christ established in His Church under the New Testament?"
[[sections]]
text = "Under the New Testament, Christ has established in the Church only two sacraments: baptism and the Lord's Supper."
verses = "Matthew 28:19; 1 Corinthians 11:20, 23-26; Matthew 26:26-28"
