id = "152"
question = "What is baptism?"
[[sections]]
text = "Baptism is a sacrament of positive and sovereign institution of the New Testament, ordained and appointed by Jesus Christ to be continued in His church to the end of the world."
verses = "Matthew 28:19-20"
[[sections]]
text = "For believers, baptism is a sign of our union and fellowship with Christ,"
verses = "Galatians 3:27; Romans 6:3-5; Colossians 2:12"
[[sections]]
text = "of the remission of our sins through His blood,"
verses = "Mark 1:4; Acts 22:16"
[[sections]]
text = "of regeneration by His Spirit,"
verses = "Titus 3:5; Ephesians 5:26; John 3:5"
[[sections]]
text = "of adoption,"
verses = "Galatians 3:26-27"
[[sections]]
text = "resurrection unto everlasting life,"
verses = "1 Corinthians 15:29; Romans 6:5"
[[sections]]
text = "and of giving up into God, through Jesus Christ, to live and walk in newness of life."
verses = "Romans 6:4"
