id = "153"
question = "How should baptism be administered?"
[[sections]]
text = "Those who are appointed to preach the gospel are the ones who are appointed to baptize."
verses = "Matthew 28:19; Mark 16:15-16"
[[sections]]
text = "The outward element to be used in this sacrament is water, wherein the party is to be baptized, in the name of the Father, and of the Son, and of the Holy Spirit."
verses = "Matthew 28:19-20; Acts 8:38"
[[sections]]
text = "Immersion, or dipping of the parson in water, is necessary to the due administration of this sacrament."
verses = "Matthew 3:16; John 3:23; Acts 8:38-39; Romans 6:4; Colossians 2:12"
