id = "154"
question = "How do we continue to use our baptism?"
[[sections]]
text = "We have a necessary but frequently neglected obligation to use our baptism our whole lives, particularly in times of temptation and when we are present at the baptism of others."
verses = "Colossians 2:11-12; Romans 6:4-6, 11; Psalm 22:10-11"
[[sections]]
text = "We should seriously and thankfully reflect on what is involved in baptism, why Christ established it, the privileges and benefits conferred and signified by it, and the significance of our own solemn vows when we were baptized."
verses = "Romans 6:3-5"
[[sections]]
text = "This reflection humbles us when we recognize how defiled we are by sin and how far short we fall of living up to, and indeed walk so contrary to the standards set by the grace of baptism and by our other spiritual commitments."
verses = "1 Corinthians 1:11-13; Romans 6:2-3"
[[sections]]
text = "We are also assured of pardon from sin and of all the other blessings signified in that sacrament."
verses = "Romans 4:11-12; 1 Peter 3:21"
[[sections]]
text = "We draw strength from the death and resurrection of Christ, into whom we were baptized, in order to keep killing our sins and becoming alive by His grace."
verses = "Romans 6:2-5"
[[sections]]
text = "We are also spurred on to live by faith,"
verses = "Galatians 3:26-27"
[[sections]]
text = "to have our human relationships defined by holiness and righteousness,"
verses = "Romans 6:22"
[[sections]]
text = "as is proper for those who have given up their names to Christ,"
verses = "Acts 2:38"
[[sections]]
text = "and to walk with each other in brotherly love, as is proper for those baptized by the same Spirit into one body."
verses = "1 Corinthians 12:13, 25-27"
