id = "155"
question = "Who should be baptized?"
[[sections]]
text = "Those who do actually profess repentance towards God, faith in, and obedience to, our Lord Jesus Christ, are the only proper subjects of this sacrament. The infants of believing parents are not to be baptized because there is neither command nor example in the Holy Scriptures nor necessary consequence from the Scripture to baptism them."
verses = "Mark 16:16; Acts 8:36-37; Acts 2:41; Acts 8:12; Acts 18:8; Acts 16:29-34"
