id = "156"
question = "Were not infants baptized when whole households were baptized?"
[[sections]]
text = "For the cases of household baptisms,"
verses = "Acts 16:14-15; Acts 16:30-34"
[[sections]]
text = "it does not appear that there were infants in the homes since the word of the gospel was spoken to the entire household;"
verses = "Acts 16:32"
[[sections]]
text = "the whole household rejoiced, believing in God;"
verses = "Acts 16:34"
[[sections]]
text = "and elsewhere the whole house is said to do that which infants could not do. Thus, the apostles give no command, example, or inference to baptize the infants of believers."
verses = "Acts 18:8; Acts 10:2; 1 Corinthians 16:15; 1 Corinthians 1:16; John 4:53"
