id = "157"
question = "Did not baptism come to replace of circumcision and thus, should be administered as it was?"
[[sections]]
text = "Baptism does not replace circumcision, but rather regeneration by the Spirit, the circumcision made without hands (commonly called spiritual circumcision),"
verses = "Philippians 3:2-3; Romans 2:28-29; Deuteronomy 30:6; Deuteronomy 10:16"
[[sections]]
text = "replaces physical circumcision as the seal of the covenant of grace."
verses = "Ephesians 1:13-14; 2 Corinthians 1:21-22; Jeremiah 31:31-34"
[[sections]]
text = "Baptism is mentioned with faith as the means whereby we are in Christ, and complete in Him. Thus, we should not administer baptism according to the rules of administration for circumcision."
verses = "Colossians 2:11-12"
