id = "158"
question = "If Abraham's physical descendants were circumcised under the Old Covenant, why shouldn't the children of believing parents be baptized under the New Covenant?"
[[sections]]
text = "The children of believers are not Abraham's true offspring by virtual of physical birth, but only by virtue of faith in Christ."
verses = "Galatians 3:7-9"
[[sections]]
text = "We know that the covenant made with Abraham consisted of two parts. In the first part, Abraham's natural offspring through Isaac constituted the nation of Israel, and through this covenant, God promised the land of Canaan"
verses = "Genesis 15:18; Genesis 17:7-8; Genesis 12:6-7; Genesis 13:14-17"
[[sections]]
text = "and other temporal national blessings, conditioned on circumcision and their obedience to the Law."
verses = "Genesis 17:9-11; Deuteronomy 28"
[[sections]]
text = "In the second part, Abraham's spiritual offspring constituted the Church, and through this covenant, God promised eternal life and other spiritual blessings, conditioned only by faith in Christ."
verses = "Romans 2:28-29; Romans 4:9-14; Philippians 3:3; Galatians 3:26-28; Galatians 4:21-30"
[[sections]]
text = "Therefore, it's an error to confound the national covenant with the covenant of grace (which the Abrahamic covenant typified), and the commonwealth of Israel founded on the first covenant with the Church founded on the second covenant. This implies that the children of believers are not in the covenant of grace by birth, but only by virtue of faith in Christ, and thus, should not receive the sacraments of the covenant."
verses = ""