id = "159"
question = "What is the duty of those who are rightly baptized?"
[[sections]]
text = "It is the duty of those who are rightly baptized to join themselves to a visible and orderly church of Jesus Christ so that they may walk in all the commandments and ordinances of the Lord."
verses = "Acts 2:46-47; Acts 9:26; 1 Peter 2:5; Hebrews 10:25; Romans 16:5"
