id = "160"
question = "What is the visible church?"
[[sections]]
text = "The visible church is the organized gathering of professing believers, in all ages and places, wherein the gospel is truly preached and the sacraments of baptism and Lord's Supper are rightly administered."
verses = "Acts 2:42; Acts 20:7; Acts 7:38; Ephesians 4:11-12"
