id = "161"
question = "What are the special privileges of the visible church?"
[[sections]]
text = "The visible church has the privilege of being under God's special care and government"
verses = "Isaiah 4:5-6; Isaiah 49:14-16; 1 Timothy 4:10; 1 Corinthians 12:28; Ephesians 4:11-12; Acts 13:1-2"
[[sections]]
text = "and of being protected and preserved throughout the ages, in spite of the opposition of all her enemies."
verses = "Psalm 115; Isaiah 31:4-5; Zechariah 12:2-4, 8-9; Matthew 16:18"
[[sections]]
text = "The visible church also provides fellowship for God's people, functions as the ordinary means by which people are saved,"
verses = "Acts 2:39-42"
[[sections]]
text = "and extends God's grace through Christ to all her members in the ministry of the gospel, testifying that whosoever believes in him will be saved"
verses = "Psalm 147:19-20; Romans 9:4; Ephesians 4:11-12; Mark 16:15-16; Acts 16:31; Revelation 22:17"
[[sections]]
text = "and excluding no one from fellowship who desires to come to Christ."
verses = "John 6:37"
