id = "162"
question = "Is everyone saved who hears the gospel and attends church?"
[[sections]]
text = "Not everyone who hears the gospel and attends a visible church is saved. The elect are only the true members of the invisible church."
verses = "John 12:38-40; Romans 9:6; Matthew 22:14; Matthew 7:21; Matthew 13:41-42; Romans 11:7"
