id = "163"
question = "What is the invisible church?"
[[sections]]
text = "The invisible church consists of the whole number of the elect, in all ages and places, gathered into one under Christ, the head."
verses = "Ephesians 1:10,22-23; John 10:16; John 11:52; Ephesians 5:23-32; Revelation 7:9; Isaiah 59:21"
