id = "164"
question = "What are the special privileges of the invisible church?"
[[sections]]
text = "The members of the invisible church have the privilege of enjoying union with Christ, whereby they are spiritually joined to Christ as their head, and thus, partake of the power of His mediation in all things which manifests their union with Christ."
verses = "1 Corinthians 6:17; John 10:28; John 15:1-5; Ephesians 5:23, 30"
[[sections]]
text = "The members of the invisible church enjoy the firstfruits of communion in the glory that Christ fully possesses"
verses = "Ephesians 2:5-6; Romans 5:1-2, 5; 2 Corinthians 1:22; Romans 14:17; 2 Peter 3:18"
[[sections]]
text = "and enjoy the full fruits of their communion in Christ following death, whereby they receive full redemption of their bodies"
verses = "Romans 8:23; Psalm 16:9"
[[sections]]
text = "and complete holiness of their souls."
verses = "Hebrews 12:23; Acts 7:55-59"
