id = "165"
question = "What is the Lord's Supper?"
[[sections]]
text = "The Lord's Supper is a sacrament of the New Testament"
verses = "Luke 22:20"
[[sections]]
text = "in which bread and wine are given and received as Christ directed to proclaim his death. Those who receive the Lord's Supper in the right way feed on his body and blood and thereby are spiritually nourished and grow in grace."
verses = "Matthew 26:26-28; 1 Corinthians 11:23-27"
[[sections]]
text = "They have their union and communion with Christ confirmed,"
verses = "1 Corinthians 10:16"
[[sections]]
text = "and they publicly witness to and repeat anew their thankfulness"
verses = "1 Corinthians 11:24"
[[sections]]
text = "and commitment to God"
verses = "1 Corinthians 10:14-16, 21"
[[sections]]
text = "and their mutual love and fellowship with each other, as members of the same mystical body."
verses = "1 Corinthians 10:17"
