id = "167"
question = "How do those who receive the Lord's Supper in the right way feed on the body and blood of Christ?"
[[sections]]
text = "The body and blood of Christ are not present in bodily or physical form, either in, with, or under the bread and wine in the Lord's supper."
verses = "Acts 3:21"
[[sections]]
text = "They are, however, spiritually present to the faith of the recipient just as truly as the external elements are obvious to the senses."
verses = "Matthew 26:26-28; Galatians 3:1; Hebrews 11:1"
[[sections]]
text = "And so those who receive the Lord's Supper in the right way do truly and actually feed on the body and blood of Christ, not in a bodily or physical way, but spiritually,"
verses = "1 Corinthians 11:24-29; John 6:51-53"
[[sections]]
text = "while by faith they receive and apply to themselves Christ crucified, along with all the benefits of his death."
verses = "1 Corinthians 10:16"
