id = "168"
question = "How do we prepare to receive the Lord's Supper?"
[[sections]]
text = "Preparation for the Lord's Supper involves careful examination:"
verses = "1 Corinthians 11:28"
[[sections]]
text = "of the condition of our life in Christ;"
verses = "2 Corinthians 13:5"
[[sections]]
text = "of our sins and failings;"
verses = "1 Corinthians 5:7; Exodus 12:15"
[[sections]]
text = "of whether we truly and to what degree know God,"
verses = "1 Corinthians 11:29"
[[sections]]
text = "believe in Him,"
verses = "2 Corinthians 13:5; Matthew 26:28"
[[sections]]
text = "and have repented,"
verses = "Zechariah 12:10; 1 Corinthians 11:31"
[[sections]]
text = "and of whether we love God and our fellow believers."
verses = "1 Corinthians 10:16-17; Acts 2:46-47"
[[sections]]
text = "We should have a charitable attitude toward everyone,"
verses = "1 Corinthians 5:8; 1 Corinthians 11:18-20"
[[sections]]
text = "including forgiveness of those who have wronged us."
verses = "Matthew 5:23-24"
[[sections]]
text = "We must also assess how much we desire Christ"
verses = "Isaiah 55:1; John 7:37; Luke 1:53"
[[sections]]
text = "and whether we are living in newness of obedience."
verses = "1 Corinthians 5:7-8"
[[sections]]
text = "Finally we must renew the practice of these graces in us"
verses = "1 Corinthians 11:25-28; Hebrews 10:21-24; Psalm 26:6"
[[sections]]
text = "by serious meditation"
verses = "1 Corinthians 11:24-25"
[[sections]]
text = "and fervent prayer."
verses = "2 Chronicles 30:18-19; Matthew 26:26"
