id = "169"
question = "Should those who have doubts about their position in Christ or about whether they are ready to take communion come to the Lord's Supper anyway?"
[[sections]]
text = "Those who have doubts about their position in Christ or about their readiness to take communion may nonetheless have a valid interest in Christ, even though they are not yet assured of being in him."
verses = "Isaiah 50:10; 1 John 5:13; Psalm 88; Psalm 77:1-12; Jonah 2:4-7"
[[sections]]
text = "In God's view, if such people are aware of and grieved by their lack of assurance,"
verses = "Isaiah 54:7-10; Matthew 5:3-4; Psalm 31:22; Psalm 73:13, 22-23"
[[sections]]
text = "sincerely want to be found in Christ,"
verses = "Philippians 3:8-9; Psalm 10:17; Psalm 42:1-2, 5, 11"
[[sections]]
text = "and want to get away from sinning,"
verses = "2 Timothy 2:19; Isaiah 50:10; Psalm 66:18-20; Romans 7:24-25"
[[sections]]
text = "and (since promises are involved in the sacrament, and it has been established to aid even weak and doubting Christians)"
verses = "Isaiah 40:11, 29, 31; Matthew 11:28; Matthew 12:20; Matthew 26:28"
[[sections]]
text = "if people in that condition are truly sorry for their lack of faith"
verses = "Mark 9:24"
[[sections]]
text = "and work hard to resolve their doubts,"
verses = "Acts 2:37; Acts 9:6; Acts 16:30"
[[sections]]
text = "they may and ought to come to the Lord's supper, so that their faith may be further strengthened."
verses = "Romans 4:11; 1 Corinthians 11:28; Matthew 11:28"