id = "170"
question = "Should the Lord's Supper be withheld from anyone who professes the faith and wants to come to it?"
[[sections]]
text = "The sacrament should and must be withheld by the authority Christ has left in his church from those whose profession of faith is based on spiritual ignorance or whose lives have scandalized the church,"
verses = "1 Corinthians 11:27-31; Matthew 7:6; 1 Corinthians 5; Jude 23; 1 Timothy 5:22"
[[sections]]
text = "until they are properly instructed and demonstrate by their behavior that they have reformed their lives."
verses = "2 Corinthians 2:5-8; 1 Corinthians 5:4-5"