id = "171"
question = "How must we receive the Lord's Supper when it's offered?"
[[sections]]
text = "In receiving the Lord's supper when it is offered, we should reverently and attentively wait on God,"
verses = "Leviticus 10:3; Hebrews 12:28; Psalm 5:7; 1 Corinthians 11:17, 26-27"
[[sections]]
text = "as we carefully observe the sacramental elements and their administration."
verses = "Exodus 24:8; Matthew 26:28; Galatians 3:1"
[[sections]]
text = "We should take specific notice of the Lord's body"
verses = "1 Corinthians 11:29"
[[sections]]
text = "and meditate feelingly on his death and suffering"
verses = "Luke 22:19"
[[sections]]
text = "and so stir up in us a lively effect of God's spiritual gifts."
verses = "1 Corinthians 11:26; 1 Corinthians 10:3-5, 11, 14"
[[sections]]
text = "We should critically examine ourselves"
verses = "1 Corinthians 11:31"
[[sections]]
text = "and be sorry for our sins."
verses = "Zechariah 12:10"
[[sections]]
text = "We should earnestly hunger and thirst after Christ,"
verses = "Revelation 22:17; Psalm 63:1-2"
[[sections]]
text = "feeding on him by faith,"
verses = "John 6:35; Galatians 2:20"
[[sections]]
text = "drawing from his fullness,"
verses = "John 1:16; Colossians 1:19"
[[sections]]
text = "trusting in his merit,"
verses = "Philippians 1:16; Philippians 3:9"
[[sections]]
text = "rejoicing in his love,"
verses = "Psalm 36:4-5; 2 Chronicles 30:21; 1 Peter 1:8"
[[sections]]
text = "and giving thanks for his grace."
verses = "Psalm 22:26"
[[sections]]
text = "We thereby renew our covenant with God"
verses = "Jeremiah 50:5; Psalm 50:5"
[[sections]]
text = "and our love for fellow believers."
verses = "Acts 2:42; 1 Corinthians 10:17"
