id = "172"
question = "What should we do after we have received the Lord's Supper?"
[[sections]]
text = "After receiving the Lord's Supper, we should think about our participation in the sacrament and whether we got anything out of it."
verses = "Psalm 28:7; Psalm 85:8; 1 Corinthians 11:17, 30-31"
[[sections]]
text = "If we have been spiritually renewed and comforted in that participation, we should bless God for it,"
verses = "2 Chronicles 30:21-23, 25-26; Acts 2:42, 46-47; 2 Corinthians 2:14"
[[sections]]
text = "pray for the effect to continue,"
verses = "Psalm 36:10; 1 Chronicles 29:18"
[[sections]]
text = "watch out for relapses,"
verses = "1 Corinthians 10:3-5, 12; Romans 11:20"
[[sections]]
text = "fulfill our vows,"
verses = "Psalm 50:14"
[[sections]]
text = "and be encouraged to take communion frequently."
verses = "1 Corinthians 11:25-26; Acts 2:42, 46; Psalm 27:4"
[[sections]]
text = "If, on the other hand, we have not received any immediate benefit from our participation, we should more carefully go over how we prepared for and participated in the sacrament."
verses = "Ecclesiastes 5:1-6; Psalm 77:6; Psalm 139:23-24"
[[sections]]
text = "If this review reveals no fault in us before God and our own conscience, then we should wait for the spiritual fruit of participation to come to us in due time."
verses = "Psalm 123:1-2; Psalm 42:5,8; Psalm 43:3-5; Isaiah 8:17"
[[sections]]
text = "However, if such a review finds us at fault in either preparing for or participating in the sacrament, we must humbly"
verses = "2 Chronicles 30:18-19; Hosea 14:2; Hosea 6:1-2"
[[sections]]
text = "resolve to be more careful and diligent in the future."
verses = "2 Chronicles 7:11; 1 Chronicles 15:12-14"
