id = "173"
question = "In what ways do the sacraments of baptism and the Lord's Supper coincide?"
[[sections]]
text = "The sacraments of baptism and the Lord's Supper coincide in that God is the author of both,"
verses = "Matthew 28:19; 1 Corinthians 11:23"
[[sections]]
text = "and the spiritual part of both is Christ and His benefits."
verses = "Romans 6:3-4; 1 Corinthians 10:16"
[[sections]]
text = "Both are seals of the same covenant,"
verses = "Romans 4:11; Colossians 2:11-12; Matthew 26:27-28"
[[sections]]
text = "are ordinarily to be administered by ministers of the gospel,"
verses = "John 1:33; Matthew 28:19; 1 Corinthians 11:23; Hebrews 5:4"
[[sections]]
text = "and are to continue in Christ's church until the second coming."
verses = "Matthew 28:19-20; 1 Corinthians 11:26"
