id = "174"
question = "In what ways do the sacraments of baptism and the Lord's Supper differ?"
[[sections]]
text = "The sacraments of baptism and the Lord's Supper differ in that baptism is administered just once, with water, as a sign and seal of our regeneration and engrafting into Christ."
verses = "Matthew 3:11; Titus 3:5; Galatians 3:27"
[[sections]]
text = "The Lord's Supper, on the other hand, is to be administered repeatedly with the elements of bread and wine, to represent and display Christ as spiritual food for the soul"
verses = "1 Corinthians 11:23-26; Colossians 2:19"
[[sections]]
text = "and to confirm our continuing growth in Him."
verses = "1 Corinthians 10:16; John 6:51-53"
