id = "175"
question = "What is prayer?"
[[sections]]
text = "Prayer is offering our desires to God"
verses = "Psalm 62:8"
[[sections]]
text = "in the name of Christ"
verses = "John 16:23-24"
[[sections]]
text = "with the help of His Spirit,"
verses = "Romans 8:26"
[[sections]]
text = "confessing our sins,"
verses = "Psalm 32:5-6; Daniel 9:4"
[[sections]]
text = "and thankfully recognizing His mercies."
verses = "Philippians 4:6"
