id = "176"
question = "Should we pray only to God?"
[[sections]]
text = "God is the only one capable of searching human hearts,"
verses = "1 Kings 8:39; Acts 1:24; Romans 8:27"
[[sections]]
text = "the only one who hears requests,"
verses = "Psalm 65:2"
[[sections]]
text = "pardons sins,"
verses = "Micah 7:18"
[[sections]]
text = "and fulfills the desires of everyone,"
verses = "Psalm 145:16, 18-19"
[[sections]]
text = "and He is the only one to believe in"
verses = "Romans 10:14; 2 Samuel 22:32; John 14:1"
[[sections]]
text = "and truly worshiped."
verses = "Matthew 4:10"
[[sections]]
text = "Since prayer is an integral part of religious worship,"
verses = "1 Corinthians 1:2"
[[sections]]
text = "it is to be made by everyone only to Him"
verses = "Psalm 50:15; Luke 4:8"
[[sections]]
text = "and to no one else."
verses = "Romans 10:14; Isaiah 42:8; Jeremiah 3:23"
