id = "177"
question = "What is the significance of praying in Christ's name?"
[[sections]]
text = "When we pray in Christ's name, we obey His command and confidently rely on His promises as a basis for requesting mercy for His sake."
verses = "John 14:13-14; John 16:24; Daniel 9:17"
[[sections]]
text = "This involves not just mentioning His name"
verses = "Matthew 7:21; Luke 6:46"
[[sections]]
text = "but drawing our encouragement to pray and our boldness, strength, and hope that our prayers will be answered from Christ Himself and His mediation."
verses = "Hebrews 4:14-16; 1 John 5:13-15"