id = "178"
question = "Why must we pray in Christ's name?"
[[sections]]
text = "Human sinfulness has so far separated us from God that we cannot gain access to His presence without a mediator to bridge that separation,"
verses = "John 14:6; Isaiah 59:2; Ephesians 3:12"
[[sections]]
text = "and since no one in heaven or earth has been appointed to or is fit for that glorious job except Christ alone,"
verses = "John 6:27; Hebrews 7:25-27; 1 Timothy 2:5"
[[sections]]
text = "we must pray in His name only and in no other."
verses = "Colossians 3:17; Hebrews 13:15"