id = "179"
question = "How does the Spirit help us to pray?"
[[sections]]
text = "Since we do not know what we ought to pray for, the Spirit helps our weakness by enabling us to understand for whom, for what, and how to pray. He works in and makes our hearts alive (although not in everyone, nor all the time, nor to the same degree) to grasp, feel, and experience the gifts that are needed to pray properly."
verses = "Romans 8:26-27; Psalm 10:17; Psalm 80:18; Zechariah 12:10"
