id = "181"
question = "For what should we pray?"
[[sections]]
text = "We should pray for things that promote the glory of God,"
verses = "Matthew 6:9"
[[sections]]
text = "the welfare of the church,"
verses = "Psalm 51:18; Psalm 122:6"
[[sections]]
text = "and our own"
verses = "Matthew 7:11"
[[sections]]
text = "or others' good,"
verses = "Psalm 125:4, 1 Thessalonians 5:23; 2 Thessalonians 3:16"
[[sections]]
text = "but not for anything that is unlawful."
verses = "1 John 5:14; James 4:3"