id = "182"
question = "How should we pray?"
[[sections]]
text = "In prayer, we should approach God with a reverent awareness of His majesty"
verses = "Ecclesiastes 5:1; Psalm 33:8; Psalm 95:6"
[[sections]]
text = "and a deep sense of our unworthiness,"
verses = "Genesis 18:27; Genesis 32:10; Psalm 144:3"
[[sections]]
text = "inadequacies,"
verses = "Luke 15:17-19; Psalm 86:1"
[[sections]]
text = "and sins."
verses = "Luke 18:13-14; Psalm 130:3"
[[sections]]
text = "Our hearts should be filled with repentance,"
verses = "Psalm 51:17; Zechariah 12:10-14"
[[sections]]
text = "thanks,"
verses = "Philippians 4:6; 1 Thessalonians 5:18"
[[sections]]
text = "and confidence,"
verses = "1 Samuel 1:15; 1 Samuel 2:1; Psalm 81:10; Ephesians 3:20-21"
[[sections]]
text = "and our prayers should be marked by understanding,"
verses = "1 Corinthians 14:15"
[[sections]]
text = "faith,"
verses = "Mark 11:24; James 1:6; Hebrews 10:22"
[[sections]]
text = "sincerity,"
verses = "Psalm 145:18; Psalm 17:1; Hebrews 10:22; John 4:24"
[[sections]]
text = "fervor,"
verses = "James 5:16"
[[sections]]
text = "love,"
verses = "1 Timothy 2:8; Matthew 5:23-24"
[[sections]]
text = "and perseverance,"
verses = "Ephesians 6:18"
[[sections]]
text = "while we wait on Him"
verses = "Micah 7:7"
[[sections]]
text = "and humbly submit to His will."
verses = "Matthew 26:39"