id = "183"
question = "What rule has God given for our direction in prayer?"
[[sections]]
text = "The whole Word of God is of use to direct us in prayer,"
verses = "1 John 5:14; 2 Timothy 3:16-17"
[[sections]]
text = "but the special rule of direction is that prayer, which Christ taught His disciples, commonly called the Lord's Prayer."
verses = "Matthew 6:9-13; Luke 11:2-4"
[[sections]]
text = "The Lord's Prayer not only direct us as a model for our other prayers but may also be used as a prayer itself that will promote our understanding, faith, reverence, and the other gifts of God in us that are necessary for us to pray properly."
verses = "Matthew 6:9; Luke 11:2"
