id = "184"
question = "What does the preface of the Lord's Prayer teach us?"
[[sections]]
text = "The preface of the Lord's prayer, Our Father in heaven,"
verses = "Matthew 6:9"
[[sections]]
text = "teaches us that when we pray we should draw near to God, confident of His fatherly goodness and the benefits to us from that goodness,"
verses = "Luke 11:13; Romans 8:15"
[[sections]]
text = "reverently and in every way like a child,"
verses = "Isaiah 64:9; Psalm 95:6-7"
[[sections]]
text = "and with heavenly feelings"
verses = "Psalm 123:1; Lamentations 3:41"
[[sections]]
text = "and a proper awareness of His sovereign power, His majesty, and His graciousness in allowing us to approach Him."
verses = "Isaiah 63:15-16; Nehemiah 1:4-6; Psalm 104:1; Psalm 113:4-6"
[[sections]]
text = "The preface also teaches us to pray with and for others."
verses = "Acts 12:5; Zechariah 8:21"