id = "185"
question = "What do we pray for in the first petition?"
[[sections]]
text = "In the first petition, hallowed be Your name,"
verses = "Matthew 6:9"
[[sections]]
text = "we acknowledge that we and all human beings are completely incapable of honoring God properly and are even disinclined to do so."
verses = "2 Corinthians 3:5; Psalm 51:15"
[[sections]]
text = "We pray then that He would by His grace enable and incline us and others to know, to acknowledge, and to esteem Him highly,"
verses = "Psalm 67:2-3; Psalm 72:19; Ephesians 3:20-21"
[[sections]]
text = "His titles,"
verses = "Psalm 83:18"
[[sections]]
text = "attributes,"
verses = "Psalm 86:10-15; Psalm 145:6-8"
[[sections]]
text = "regulations, word,"
verses = "2 Thessalonians 3:1; Psalm 107:32; Psalm 147:19-20; Psalm 138:1-3; 2 Corinthians 2:14-15"
[[sections]]
text = "works, and everything else by which He is pleased to reveal Himself,"
verses = "Psalm 145; Psalm 8"
[[sections]]
text = "and to glorify Him in thought, word,"
verses = "Psalm 103:1; Psalm 19:14"
[[sections]]
text = "and deed,"
verses = "Philippians 1:9-11"
[[sections]]
text = "to the effect that he would thwart and do away with atheism,"
verses = "Psalm 67:1-4; Psalm 79:10"
[[sections]]
text = "spiritual ignorance,"
verses = "Ephesians 1:17-18"
[[sections]]
text = "idolatry,"
verses = "Psalm 97:7"
[[sections]]
text = "or any kind of desecration,"
verses = "Psalm 74:18, 22-23"
[[sections]]
text = "and whatever else dishonors Him,"
verses = "2 Kings 19:15-16; Jeremiah 14:21"
[[sections]]
text = "and that by His invincible providence, He would direct and regulate everything to His own glory."
verses = "2 Chronicles 20:6, 10-12; Psalm 83; Psalm 140:4, 8; Isaiah 64:1-2"
