id = "186"
question = "What do we pray for in the second petition?"
[[sections]]
text = "In the second petition, Your kingdom come,"
verses = "Matthew 6:10"
[[sections]]
text = "we acknowledge that we and all humans are by nature under the dominion of sin and Satan."
verses = "Ephesians 2:2-3"
[[sections]]
text = "We pray then that the kingdom of sin and Satan be destroyed,"
verses = "Psalm 68:1, 18; Revelation 12:9-11"
[[sections]]
text = "that the gospel be preached throughout the whole world,"
verses = "2 Thessalonians 3:1"
[[sections]]
text = "that the Jews be converted,"
verses = "Romans 10:1; Psalm 67:2"
[[sections]]
text = "and that the full number of the Gentiles come in."
verses = "John 17:9, 20; Romans 11:25-26; Psalm 67"
[[sections]]
text = "We pray that the church would be supplied with evangelical officers and regulations,"
verses = "Matthew 9:38; 2 Thessalonians 3:1"
[[sections]]
text = "purged from corruption,"
verses = "Malachi 1:11; Zephaniah 3:9; Ephesians 5:26-27"
[[sections]]
text = "and recognized and supported by the civil authorities."
verses = "1 Timothy 2:1-2"
[[sections]]
text = "We pray for the regulations of Christ to be administered fully and that these regulations may effectively convert sinners, while confirming, comforting, and building up those who are already converted."
verses = "Acts 4:29-30; Acts 26:18; Ephesians 6:18-20; Romans 15:29-32; 2 Thessalonians 1:11; 2 Thessalonians 2:16-17; 2 Corinthians 4:2"
[[sections]]
text = "And we pray that Christ would rule over our hearts in the here and now,"
verses = "Ephesians 3:14-21"
[[sections]]
text = "that he would hurry up and come again, when we shall reign with him forever,"
verses = "Revelation 22:20"
[[sections]]
text = "and that he would be pleased so to rule over everything that goes on in the world as may best bring about all these results."
verses = "Isaiah 64:1-2; Revelation 4:8-11; 2 Chronicles 20:6, 10-12"
