id = "187"
question = "For what do we pray in the third petition?"
[[sections]]
text = "In the third petition, Your will be done on earth as it is in heaven,"
verses = "Matthew 6:10"
[[sections]]
text = "we acknowledge that we and all humans are by nature not only completely incapable of and unwilling to know and to do the will of God"
verses = "Romans 7:18; Romans 8:5, 8; Job 21:14; 1 Corinthians 2:14"
[[sections]]
text = "but are actively prone to rebel against His Word,"
verses = "Romans 8:7"
[[sections]]
text = "to be unhappy with and complain about his providence,"
verses = "Exodus 17:7; Numbers 14:2; Matthew 20:11-12; Psalm 73:3"
[[sections]]
text = "and are naturally inclined to follow our own selfish desires and the directions of Satan."
verses = "Ephesians 2:2-3; Titus 3:3"
[[sections]]
text = "We pray then that God would by his Spirit remove from us and others all spiritual blindness,"
verses = "Ephesians 1:17-18"
[[sections]]
text = "weakness,"
verses = "Ephesians 3:16"
[[sections]]
text = "indisposition to spiritual activities,"
verses = "Matthew 26:40-41; Romans 7:24-25"
[[sections]]
text = "and perverseness of heart,"
verses = "Jeremiah 31:18-19; Ezekiel 11:19"
[[sections]]
text = "and that he would by his grace make us willing to know, do, and submit to his will in every circumstance,"
verses = "Psalm 119:1, 8, 35-36; Acts 21:14; 1 Samuel 3:18"
[[sections]]
text = "with the same kind of humility,"
verses = "Micah 6:8; Psalm 123:2; Psalm 131:2"
[[sections]]
text = "cheerfulness,"
verses = "Psalm 100:2 Job 1:21; 2 Samuel 15:25-26"
[[sections]]
text = "faithfulness,"
verses = "Isaiah 38:3; Ephesians 6:6"
[[sections]]
text = "steadfastness,"
verses = "Psalm 119:4-5"
[[sections]]
text = "zeal,"
verses = "Romans 12:11"
[[sections]]
text = "sincerity,"
verses = "Psalm 119:80; 2 Corinthians 1:12"
[[sections]]
text = "and constancy"
verses = "Psalm 119:112; Romans 2:7"
[[sections]]
text = "that the angels have in heaven."
verses = "Isaiah 6:2-3; Psalm 103:20-22; Matthew 18:10; Daniel 7:10"
