id = "188"
question = "For what do we pray in the fourth petition?"
[[sections]]
text = "In the fourth petition, Give us today our daily bread,"
verses = "Matthew 6:11"
[[sections]]
text = "we acknowledge that in Adam and by our own sin we have forfeited any right to all of the outward blessings of this life, that we deserve to be completely deprived of them by God and to have their use by us cursed,"
verses = "Genesis 2:17; Genesis 3:17; Romans 8:20-22; Jeremiah 5:24-25; Deuteronomy 28:15-68; Lamentations 3:22"
[[sections]]
text = "and that the outward blessings of this life are not in and of themselves capable of sustaining us,"
verses = "Deuteronomy 8:3"
[[sections]]
text = "nor do we deserve"
verses = "Genesis 32:10"
[[sections]]
text = "or actually obtain them by our own efforts,"
verses = "Deuteronomy 8:17-18; Proverbs 10:22"
[[sections]]
text = "but lust after,"
verses = "Jeremiah 6:13; Mark 7:21-22; Luke 12:15"
[[sections]]
text = "acquire,"
verses = "Hosea 12:7"
[[sections]]
text = "and use them in unlawful ways."
verses = "James 4:3"
[[sections]]
text = "We pray then for ourselves and others that both they and we may wait daily on God's providential allowance of the outward blessings of this life and that, according to what his fatherly wisdom decides is best, we may lawfully enjoy his free gift of what is sufficient for us."
verses = "Genesis 43:12-14; Genesis 28:20-21; Ephesians 4:28; 2 Thessalonians 3:11-12; Philippians 4:6; James 4:13-15; Psalm 90:17; Psalm 144:12-15"
[[sections]]
text = "We also pray that God would continue to bless us with sufficient worldly goods, that they would sustain our needs and be sanctified by us,"
verses = "1 Timothy 4:3-5; Proverbs 10:22"
[[sections]]
text = "that we would be satisfied with them,"
verses = "1 Timothy 6:6-8"
[[sections]]
text = "and that God would protect us from anything that undermines our support and sustenance in this world."
verses = "Proverbs 30:8-9"
