id = "189"
question = "For what do we pray in the fifth petition?"
[[sections]]
text = "In the fifth petition, Forgive us our debts as we also have forgiven our debtors,"
verses = "Matthew 6:12"
[[sections]]
text = "we acknowledge that we and everyone else are guilty both of original sin and actual sins and are therefore debtors to God's justice, and that neither we nor any other created being can make the least satisfaction for that debt."
verses = "Romans 3:9-22; Romans 5:19; Matthew 18:24-25; Psalm 130:3-4; Micah 6:6-7"
[[sections]]
text = "We pray then for ourselves and others that of his free grace and through the obedience and satisfaction of Christ, which is grasped and applied by faith, God would acquit us from the guilt and punishment of sin,"
verses = "Romans 3:24-26; Romans 5:19; Hebrews 9:22; Acts 13:39"
[[sections]]
text = "accept us in the One he loves,"
verses = "Ephesians 1:6-7"
[[sections]]
text = "continue his favor and grace to us,"
verses = "2 Peter 1:2"
[[sections]]
text = "forgive our daily sins,"
verses = "Hosea 14:2; Jeremiah 14:7; Psalm 143:2; Psalm 130:3"
[[sections]]
text = "and fill us with the peace and joy that come from the daily gift of growing assurance of being forgiven."
verses = "Romans 15:13; Romans 5:1-2; Psalm 51:7-12"
[[sections]]
text = "We may more boldly make this request and be encouraged to expect to be forgiven, when and if we are assured in ourselves that we have genuinely, from the heart, forgiven others who have wronged us."
verses = "Luke 11:4; Matthew 6:14-15; Matthew 18:35"
