id = "190"
question = "For what do we pray in the sixth petition?"
[[sections]]
text = "In the sixth petition, And lead us not into temptation, but deliver us from the evil one,"
verses = "Matthew 6:13"
[[sections]]
text = "we acknowledge that God, who is completely wise, righteous, and gracious, may, for various holy and just purposes, ordain circumstances by which we become the target of temptations, are defeated, and temporarily taken captive by them;"
verses = "2 Chronicles 32:31; Job 2:6"
[[sections]]
text = "that Satan,"
verses = "1 Chronicles 21:1; 1 Peter 5:8; Job 2:2"
[[sections]]
text = "the world,"
verses = "Luke 21:34; Mark 4:19"
[[sections]]
text = "and our own sinful natures have a powerful potential to turn us aside from righteousness and trap us;"
verses = "James 1:14"
[[sections]]
text = "and that even after our sins have been forgiven, we are naturally so depraved,"
verses = "Galatians 5:17; Romans 7:18"
[[sections]]
text = "spiritually weak, and inattentive to our spiritual condition"
verses = "Matthew 26:41"
[[sections]]
text = "that we are not only prey to temptations and willingly expose ourselves to them"
verses = "Matthew 26:69-72; Galatians 2:11-14; 2 Chronicles 18:3; 2 Chronicles 19:2; 1 Timothy 6:9; Proverbs 7:22"
[[sections]]
text = "but are completely incapable of and unwilling to resist, get away from, or use them as opportunities for our spiritual growth"
verses = "Romans 7:18-19, 23-24; 1 Chronicles 21:1-4; 2 Chronicles 16:7-10"
[[sections]]
text = "—and consequently we deserve to be left under their power."
verses = "Psalm 81:11-12"
[[sections]]
text = "We pray then that God would so rule over the world and everyone in it,"
verses = "John 17:15; Romans 8:28"
[[sections]]
text = "so curb our sinful natures"
verses = "Psalm 51:10; Psalm 119:133"
[[sections]]
text = "and restrain Satan,"
verses = "2 Corinthians 12:7-8; Hebrews 2:18; 1 Corinthians 10:13"
[[sections]]
text = "so ordain all things,"
verses = "1 Corinthians 10:12-13; Romans 8:28"
[[sections]]
text = "so endow and bless all the means of grace"
verses = "Hebrews 13:20-21; Ephesians 4:11-12"
[[sections]]
text = "and sharpen our awareness in the use of them, that we and all his people may be providentially spared from being tempted to sin;"
verses = "Matthew 26:41; Psalm 19:13"
[[sections]]
text = "or, if tempted, that his Spirit would powerfully support and enable us to resist during the time of our temptation;"
verses = "Ephesians 3:14-17; 1 Thessalonians 3:13; Jude 24; 1 Corinthians 10:13"
[[sections]]
text = "or, should we fall, that we would be raised again and restored,"
verses = "Psalm 51:12"
[[sections]]
text = "with the experience being thereby sanctified and used for our spiritual growth;"
verses = "1 Peter 5:8-10; 1 Peter 1:6-7"
[[sections]]
text = "and that our sanctification and salvation may be made complete,"
verses = "2 Corinthians 13:7-9; 1 Thessalonians 3:13"
[[sections]]
text = "Satan trampled under our feet,"
verses = "Romans 16:20; Zechariah 3:2; Luke 22:31-32"
[[sections]]
text = "and we become completely delivered from sin, temptation, and all evil, forever."
verses = "John 17:15; 1 Thessalonians 5:23"
