id = "191"
question = "What does the conclusion of the Lord's prayer teach us?"
[[sections]]
text = "The conclusion of the Lord's prayer, for Yours is the kingdom and the power and the glory forever,"
verses = "Matthew 6:13"
[[sections]]
text = "teaches us that there must be substance to our requests,"
verses = "Romans 15:30; Job 23:3-4; Jeremiah 14:20-21"
[[sections]]
text = "that they are based not on any intrinsic worth in ourselves or any created being but on God himself,"
verses = "Daniel 9:4, 7-9, 16-19"
[[sections]]
text = "and that to our prayers should be added praise,"
verses = "Philippians 4:6"
[[sections]]
text = "which recognizes God alone as eternally sovereign, omnipotent, and gloriously excellent."
verses = "1 Chronicles 29:10-13"
[[sections]]
text = "In that respect, insofar as he is able and willing to help us,"
verses = "Ephesians 3:20-21; Luke 11:13; Psalm 84:11"
[[sections]]
text = "our faith makes us bold to plead with him that he will help us"
verses = "2 Chronicles 20:6, 11; Ephesians 3:11-12; Hebrews 10:19-22"
[[sections]]
text = "and calmly to count on him to answer our prayers."
verses = "2 Chronicles 14:11; John 5:14; Romans 8:32"
[[sections]]
text = "To show that we want to be heard and have confidence that we are heard, we say Amen."
verses = "1 Corinthians 14:16; Revelation 22:20-21"
