name: TOML to LaTeX and PDF

on:
  push:
    paths:
      - 'src/*.toml'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'  # This enables caching for pip
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml
      
      - name: Create output directory
        run: mkdir -p dist
      
      - name: Convert TOML to LaTeX
        run: python .github/scripts/toml_to_latex.py -s src -o dist/larger-catechism.tex
      
      - name: Setup TinyTeX
        uses: r-lib/actions/setup-tinytex@v2
        
      - name: Install LaTeX packages
        run: |
          tlmgr install xcolor titlesec fancyhdr fontspec setspace mdframed latex-tools enumitem tocloft bookmark hyperref
          tlmgr path add
      
      - name: Convert LaTeX to PDF (2 passes)
        run: |
          cd dist
          xelatex -interaction=nonstopmode larger-catechism.tex
          xelatex -interaction=nonstopmode larger-catechism.tex
      
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: larger-catechism-pdf
          path: dist/larger-catechism.pdf