name: TOML to LaTeX and PDF

on:
  push:
    paths:
      - 'src/*.toml'
  workflow_dispatch:  # Allow manual triggering

jobs:
  convert:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install toml
      
      - name: Create output directory
        run: mkdir -p dist
      
      - name: Convert TOML to LaTeX
        run: python .github/scripts/toml_to_latex.py -s src -o dist/larger-catechism.tex
      
      - name: Convert LaTeX to PDF
        uses: docker://texlive/texlive:latest
        with:
          entrypoint: sh
          args: -c "cd /github/workspace && xelatex -interaction=nonstopmode -output-directory=dist dist/larger-catechism.tex"
      
      - name: Run xelatex again for references
        uses: docker://texlive/texlive:latest
        with:
          entrypoint: sh
          args: -c "cd /github/workspace && xelatex -interaction=nonstopmode -output-directory=dist dist/larger-catechism.tex"
      
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: larger-catechism-pdf
          path: dist/larger-catechism.pdf